/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

class MegaTreeProcessor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MegaTreeProcessor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaTreeProcessor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaTreeProcessor(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    megaJNI.MegaTreeProcessor_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    megaJNI.MegaTreeProcessor_change_ownership(this, swigCPtr, true);
  }

  public boolean processMegaNode(MegaNode node) {
    return (getClass() == MegaTreeProcessor.class) ? megaJNI.MegaTreeProcessor_processMegaNode(swigCPtr, this, MegaNode.getCPtr(node), node) : megaJNI.MegaTreeProcessor_processMegaNodeSwigExplicitMegaTreeProcessor(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public MegaTreeProcessor() {
    this(megaJNI.new_MegaTreeProcessor(), true);
    megaJNI.MegaTreeProcessor_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
