/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaAccountDetails {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MegaAccountDetails(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaAccountDetails obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaAccountDetails(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public int getProLevel() {
    return megaJNI.MegaAccountDetails_getProLevel(swigCPtr, this);
  }

  public long getStorageMax() {
    return megaJNI.MegaAccountDetails_getStorageMax(swigCPtr, this);
  }

  public long getStorageUsed() {
    return megaJNI.MegaAccountDetails_getStorageUsed__SWIG_0(swigCPtr, this);
  }

  public long getTransferMax() {
    return megaJNI.MegaAccountDetails_getTransferMax(swigCPtr, this);
  }

  public long getTransferOwnUsed() {
    return megaJNI.MegaAccountDetails_getTransferOwnUsed(swigCPtr, this);
  }

  public long getStorageUsed(long handle) {
    return megaJNI.MegaAccountDetails_getStorageUsed__SWIG_1(swigCPtr, this, handle);
  }

  public long getNumFiles(long handle) {
    return megaJNI.MegaAccountDetails_getNumFiles(swigCPtr, this, handle);
  }

  public long getNumFolders(long handle) {
    return megaJNI.MegaAccountDetails_getNumFolders(swigCPtr, this, handle);
  }

   MegaAccountDetails copy() {
    long cPtr = megaJNI.MegaAccountDetails_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaAccountDetails(cPtr, false);
  }

  public final static int ACCOUNT_TYPE_FREE = 0;
  public final static int ACCOUNT_TYPE_PROI = 1;
  public final static int ACCOUNT_TYPE_PROII = 2;
  public final static int ACCOUNT_TYPE_PROIII = 3;

}
