/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class mega {
  public static String getMEGA_DEBRIS_FOLDER() {
    return megaJNI.MEGA_DEBRIS_FOLDER_get();
  }

  public static long getINVALID_HANDLE() {
    return megaJNI.INVALID_HANDLE_get();
  }

}
