/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaTransfer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MegaTransfer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaTransfer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaTransfer(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaTransfer copy() {
    long cPtr = megaJNI.MegaTransfer_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaTransfer(cPtr, true);
  }

  public int getType() {
    return megaJNI.MegaTransfer_getType(swigCPtr, this);
  }

  public String getTransferString() {
    return megaJNI.MegaTransfer_getTransferString(swigCPtr, this);
  }

  public String toString() {
    return megaJNI.MegaTransfer_toString(swigCPtr, this);
  }

  public String __str__() {
    return megaJNI.MegaTransfer___str__(swigCPtr, this);
  }

  public long getStartTime() {
    return megaJNI.MegaTransfer_getStartTime(swigCPtr, this);
  }

  public long getTransferredBytes() {
    return megaJNI.MegaTransfer_getTransferredBytes(swigCPtr, this);
  }

  public long getTotalBytes() {
    return megaJNI.MegaTransfer_getTotalBytes(swigCPtr, this);
  }

  public String getPath() {
    return megaJNI.MegaTransfer_getPath(swigCPtr, this);
  }

  public String getParentPath() {
    return megaJNI.MegaTransfer_getParentPath(swigCPtr, this);
  }

  public long getNodeHandle() {
    return megaJNI.MegaTransfer_getNodeHandle(swigCPtr, this);
  }

  public long getParentHandle() {
    return megaJNI.MegaTransfer_getParentHandle(swigCPtr, this);
  }

  public long getStartPos() {
    return megaJNI.MegaTransfer_getStartPos(swigCPtr, this);
  }

  public long getEndPos() {
    return megaJNI.MegaTransfer_getEndPos(swigCPtr, this);
  }

  public String getFileName() {
    return megaJNI.MegaTransfer_getFileName(swigCPtr, this);
  }

  public int getNumRetry() {
    return megaJNI.MegaTransfer_getNumRetry(swigCPtr, this);
  }

  public int getMaxRetries() {
    return megaJNI.MegaTransfer_getMaxRetries(swigCPtr, this);
  }

  public int getTag() {
    return megaJNI.MegaTransfer_getTag(swigCPtr, this);
  }

  public long getSpeed() {
    return megaJNI.MegaTransfer_getSpeed(swigCPtr, this);
  }

  public long getDeltaSize() {
    return megaJNI.MegaTransfer_getDeltaSize(swigCPtr, this);
  }

  public long getUpdateTime() {
    return megaJNI.MegaTransfer_getUpdateTime(swigCPtr, this);
  }

  public MegaNode getPublicMegaNode() {
    long cPtr = megaJNI.MegaTransfer_getPublicMegaNode(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public boolean isSyncTransfer() {
    return megaJNI.MegaTransfer_isSyncTransfer(swigCPtr, this);
  }

  public boolean isStreamingTransfer() {
    return megaJNI.MegaTransfer_isStreamingTransfer(swigCPtr, this);
  }

  public String getLastBytes() {
    return megaJNI.MegaTransfer_getLastBytes(swigCPtr, this);
  }

  public final static int TYPE_DOWNLOAD = 0;
  public final static int TYPE_UPLOAD = TYPE_DOWNLOAD + 1;

}
