//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MegaApp.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must agree with our terms of use.
        /// </summary>
        internal static string AgreeTermsOfUse {
            get {
                return ResourceManager.GetString("AgreeTermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terms of use.
        /// </summary>
        internal static string AgreeTermsOfUse_Title {
            get {
                return ResourceManager.GetString("AgreeTermsOfUse_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to confirm account. Please try again. [{0}].
        /// </summary>
        internal static string ConfirmAccountFailed {
            get {
                return ResourceManager.GetString("ConfirmAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm account failed.
        /// </summary>
        internal static string ConfirmAccountFailed_Title {
            get {
                return ResourceManager.GetString("ConfirmAccountFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been created, confirmed and activated. You can now login..
        /// </summary>
        internal static string ConfirmAccountSucces {
            get {
                return ResourceManager.GetString("ConfirmAccountSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account activated.
        /// </summary>
        internal static string ConfirmAccountSucces_Title {
            get {
                return ResourceManager.GetString("ConfirmAccountSucces_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check your e-mail and click the link to login and confirm your account.
        /// </summary>
        internal static string ConfirmNeeded {
            get {
                return ResourceManager.GetString("ConfirmNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation needed.
        /// </summary>
        internal static string ConfirmNeeded_Title {
            get {
                return ResourceManager.GetString("ConfirmNeeded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA Cloud Drive account creation failed. Please try again. [{0}].
        /// </summary>
        internal static string CreateAccountFailed {
            get {
                return ResourceManager.GetString("CreateAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account creation failed.
        /// </summary>
        internal static string CreateAccountFailed_Title {
            get {
                return ResourceManager.GetString("CreateAccountFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to create folder.
        /// </summary>
        internal static string CreateFolderFailed {
            get {
                return ResourceManager.GetString("CreateFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folder creation failed.
        /// </summary>
        internal static string CreateFolderFailed_Title {
            get {
                return ResourceManager.GetString("CreateFolderFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folder created successful.
        /// </summary>
        internal static string CreateFolderSuccess {
            get {
                return ResourceManager.GetString("CreateFolderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folder created.
        /// </summary>
        internal static string CreateFolderSuccess_Title {
            get {
                return ResourceManager.GetString("CreateFolderSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed tot delete item. Please try again.
        /// </summary>
        internal static string DeleteNodeFailed {
            get {
                return ResourceManager.GetString("DeleteNodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete failed.
        /// </summary>
        internal static string DeleteNodeFailed_Title {
            get {
                return ResourceManager.GetString("DeleteNodeFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to retrieve a download link. Please try again.
        /// </summary>
        internal static string DownloadLinkFailed {
            get {
                return ResourceManager.GetString("DownloadLinkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retrieving link failed.
        /// </summary>
        internal static string DownloadLinkFailed_Title {
            get {
                return ResourceManager.GetString("DownloadLinkFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to download file. Please try again.
        /// </summary>
        internal static string DownloadNodeFailed {
            get {
                return ResourceManager.GetString("DownloadNodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download failed.
        /// </summary>
        internal static string DownloadNodeFailed_Title {
            get {
                return ResourceManager.GetString("DownloadNodeFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not retrieve files and folders from MEGA. Please try again..
        /// </summary>
        internal static string FetchingNodesFailed {
            get {
                return ResourceManager.GetString("FetchingNodesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fetching data failed.
        /// </summary>
        internal static string FetchingNodesFailed_Title {
            get {
                return ResourceManager.GetString("FetchingNodesFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to create folder. Please try again.
        /// </summary>
        internal static string FolderCreateFailed {
            get {
                return ResourceManager.GetString("FolderCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folder creation failed.
        /// </summary>
        internal static string FolderCreateFailed_Title {
            get {
                return ResourceManager.GetString("FolderCreateFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have successfully logged out.
        /// </summary>
        internal static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logged out.
        /// </summary>
        internal static string LoggedOut_Title {
            get {
                return ResourceManager.GetString("LoggedOut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEGA Cloud Drive login failed. Please try again. [{0}].
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login failed.
        /// </summary>
        internal static string LoginFailed_Title {
            get {
                return ResourceManager.GetString("LoginFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to logout. Please try again. [{0}].
        /// </summary>
        internal static string LogoutFailed {
            get {
                return ResourceManager.GetString("LogoutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout failed.
        /// </summary>
        internal static string LogoutFailed_Title {
            get {
                return ResourceManager.GetString("LogoutFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destination folder is the same as the source folder. Moving canceled.
        /// </summary>
        internal static string MoveEqualsParent {
            get {
                return ResourceManager.GetString("MoveEqualsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move failed.
        /// </summary>
        internal static string MoveEqualsParent_Title {
            get {
                return ResourceManager.GetString("MoveEqualsParent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to move item. Please try again.
        /// </summary>
        internal static string MoveFailed {
            get {
                return ResourceManager.GetString("MoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move failed.
        /// </summary>
        internal static string MoveFailed_Title {
            get {
                return ResourceManager.GetString("MoveFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your passwords do not match. Please re-type them and make sure they are equal.
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        internal static string PasswordsDoNotMatch_Title {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image is saved in your photo album.
        /// </summary>
        internal static string PictureSaved {
            get {
                return ResourceManager.GetString("PictureSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Picture saved.
        /// </summary>
        internal static string PictureSaved_Title {
            get {
                return ResourceManager.GetString("PictureSaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to remove item.
        /// </summary>
        internal static string RemoveNodeFailed {
            get {
                return ResourceManager.GetString("RemoveNodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove failed.
        /// </summary>
        internal static string RemoveNodeFailed_Title {
            get {
                return ResourceManager.GetString("RemoveNodeFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item successful removed to rubbish bin.
        /// </summary>
        internal static string RemoveNodeSucces {
            get {
                return ResourceManager.GetString("RemoveNodeSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item removed.
        /// </summary>
        internal static string RemoveNodeSuccess_Title {
            get {
                return ResourceManager.GetString("RemoveNodeSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fill in required fields.
        /// </summary>
        internal static string RequiredFields_Title {
            get {
                return ResourceManager.GetString("RequiredFields_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please fill in your choosen password.
        /// </summary>
        internal static string RequiredFieldsConfirmAccount {
            get {
                return ResourceManager.GetString("RequiredFieldsConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please fill in your name, e-mail address and your new password.
        /// </summary>
        internal static string RequiredFieldsCreateAccount {
            get {
                return ResourceManager.GetString("RequiredFieldsCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please fill in your e-mail address and your MEGA password.
        /// </summary>
        internal static string RequiredFieldsLogin {
            get {
                return ResourceManager.GetString("RequiredFieldsLogin", resourceCulture);
            }
        }
    }
}
