/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mega.sdk;

public class megaJNI {

  static 
  {
    try { System.loadLibrary("mega"); } 
    catch (UnsatisfiedLinkError e1) 
    {
		try { System.load(System.getProperty("user.dir")+"/libmega.so"); }
		catch(UnsatisfiedLinkError e2)
		{
			System.err.println("Native code library failed to load. \n" + e2);
			System.exit(1);
		}
    }
  }

  public final static native String MEGA_DEBRIS_FOLDER_get();
  public final static native long INVALID_HANDLE_get();
  public final static native boolean MegaGfxProcessor_readBitmap(long jarg1, MegaGfxProcessor jarg1_, String jarg2);
  public final static native int MegaGfxProcessor_getWidth(long jarg1, MegaGfxProcessor jarg1_);
  public final static native int MegaGfxProcessor_getHeight(long jarg1, MegaGfxProcessor jarg1_);
  public final static native int MegaGfxProcessor_getBitmapDataSize(long jarg1, MegaGfxProcessor jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7);
  public final static native boolean MegaGfxProcessor_getBitmapData(long jarg1, MegaGfxProcessor jarg1_, byte[] jarg2);
  public final static native void MegaGfxProcessor_freeBitmap(long jarg1, MegaGfxProcessor jarg1_);
  public final static native void delete_MegaGfxProcessor(long jarg1);
  public final static native long new_MegaGfxProcessor();
  public final static native void MegaGfxProcessor_director_connect(MegaGfxProcessor obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MegaGfxProcessor_change_ownership(MegaGfxProcessor obj, long cptr, boolean take_or_release);
  public final static native long new_MegaProxy();
  public final static native void delete_MegaProxy(long jarg1);
  public final static native void MegaProxy_setProxyType(long jarg1, MegaProxy jarg1_, int jarg2);
  public final static native void MegaProxy_setProxyURL(long jarg1, MegaProxy jarg1_, String jarg2);
  public final static native void MegaProxy_setCredentials(long jarg1, MegaProxy jarg1_, String jarg2, String jarg3);
  public final static native int MegaProxy_getProxyType(long jarg1, MegaProxy jarg1_);
  public final static native String MegaProxy_getProxyURL(long jarg1, MegaProxy jarg1_);
  public final static native boolean MegaProxy_credentialsNeeded(long jarg1, MegaProxy jarg1_);
  public final static native String MegaProxy_getUsername(long jarg1, MegaProxy jarg1_);
  public final static native String MegaProxy_getPassword(long jarg1, MegaProxy jarg1_);
  public final static native void MegaLogger_log(long jarg1, MegaLogger jarg1_, String jarg2, int jarg3, String jarg4, String jarg5);
  public final static native void MegaLogger_logSwigExplicitMegaLogger(long jarg1, MegaLogger jarg1_, String jarg2, int jarg3, String jarg4, String jarg5);
  public final static native void delete_MegaLogger(long jarg1);
  public final static native long new_MegaLogger();
  public final static native void MegaLogger_director_connect(MegaLogger obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MegaLogger_change_ownership(MegaLogger obj, long cptr, boolean take_or_release);
  public final static native void delete_MegaNode(long jarg1);
  public final static native long MegaNode_copy(long jarg1, MegaNode jarg1_);
  public final static native int MegaNode_getType(long jarg1, MegaNode jarg1_);
  public final static native String MegaNode_getName(long jarg1, MegaNode jarg1_);
  public final static native String MegaNode_getBase64Handle(long jarg1, MegaNode jarg1_);
  public final static native long MegaNode_getSize(long jarg1, MegaNode jarg1_);
  public final static native long MegaNode_getCreationTime(long jarg1, MegaNode jarg1_);
  public final static native long MegaNode_getModificationTime(long jarg1, MegaNode jarg1_);
  public final static native long MegaNode_getHandle(long jarg1, MegaNode jarg1_);
  public final static native String MegaNode_getBase64Key(long jarg1, MegaNode jarg1_);
  public final static native int MegaNode_getTag(long jarg1, MegaNode jarg1_);
  public final static native boolean MegaNode_isFile(long jarg1, MegaNode jarg1_);
  public final static native boolean MegaNode_isFolder(long jarg1, MegaNode jarg1_);
  public final static native boolean MegaNode_isRemoved(long jarg1, MegaNode jarg1_);
  public final static native boolean MegaNode_hasThumbnail(long jarg1, MegaNode jarg1_);
  public final static native boolean MegaNode_hasPreview(long jarg1, MegaNode jarg1_);
  public final static native boolean MegaNode_isPublic(long jarg1, MegaNode jarg1_);
  public final static native void delete_MegaUser(long jarg1);
  public final static native long MegaUser_copy(long jarg1, MegaUser jarg1_);
  public final static native String MegaUser_getEmail(long jarg1, MegaUser jarg1_);
  public final static native int MegaUser_getVisibility(long jarg1, MegaUser jarg1_);
  public final static native long MegaUser_getTimestamp(long jarg1, MegaUser jarg1_);
  public final static native void delete_MegaShare(long jarg1);
  public final static native long MegaShare_copy(long jarg1, MegaShare jarg1_);
  public final static native String MegaShare_getUser(long jarg1, MegaShare jarg1_);
  public final static native long MegaShare_getNodeHandle(long jarg1, MegaShare jarg1_);
  public final static native int MegaShare_getAccess(long jarg1, MegaShare jarg1_);
  public final static native long MegaShare_getTimestamp(long jarg1, MegaShare jarg1_);
  public final static native void delete_MegaNodeList(long jarg1);
  public final static native long MegaNodeList_copy(long jarg1, MegaNodeList jarg1_);
  public final static native long MegaNodeList_get(long jarg1, MegaNodeList jarg1_, int jarg2);
  public final static native int MegaNodeList_size(long jarg1, MegaNodeList jarg1_);
  public final static native void delete_MegaUserList(long jarg1);
  public final static native long MegaUserList_copy(long jarg1, MegaUserList jarg1_);
  public final static native long MegaUserList_get(long jarg1, MegaUserList jarg1_, int jarg2);
  public final static native int MegaUserList_size(long jarg1, MegaUserList jarg1_);
  public final static native void delete_MegaShareList(long jarg1);
  public final static native long MegaShareList_get(long jarg1, MegaShareList jarg1_, int jarg2);
  public final static native int MegaShareList_size(long jarg1, MegaShareList jarg1_);
  public final static native void delete_MegaTransferList(long jarg1);
  public final static native long MegaTransferList_get(long jarg1, MegaTransferList jarg1_, int jarg2);
  public final static native int MegaTransferList_size(long jarg1, MegaTransferList jarg1_);
  public final static native void delete_MegaRequest(long jarg1);
  public final static native long MegaRequest_copy(long jarg1, MegaRequest jarg1_);
  public final static native int MegaRequest_getType(long jarg1, MegaRequest jarg1_);
  public final static native String MegaRequest_getRequestString(long jarg1, MegaRequest jarg1_);
  public final static native String MegaRequest_toString(long jarg1, MegaRequest jarg1_);
  public final static native String MegaRequest___str__(long jarg1, MegaRequest jarg1_);
  public final static native long MegaRequest_getNodeHandle(long jarg1, MegaRequest jarg1_);
  public final static native String MegaRequest_getLink(long jarg1, MegaRequest jarg1_);
  public final static native long MegaRequest_getParentHandle(long jarg1, MegaRequest jarg1_);
  public final static native String MegaRequest_getSessionKey(long jarg1, MegaRequest jarg1_);
  public final static native String MegaRequest_getName(long jarg1, MegaRequest jarg1_);
  public final static native String MegaRequest_getEmail(long jarg1, MegaRequest jarg1_);
  public final static native String MegaRequest_getPassword(long jarg1, MegaRequest jarg1_);
  public final static native String MegaRequest_getNewPassword(long jarg1, MegaRequest jarg1_);
  public final static native String MegaRequest_getPrivateKey(long jarg1, MegaRequest jarg1_);
  public final static native int MegaRequest_getAccess(long jarg1, MegaRequest jarg1_);
  public final static native String MegaRequest_getFile(long jarg1, MegaRequest jarg1_);
  public final static native int MegaRequest_getNumRetry(long jarg1, MegaRequest jarg1_);
  public final static native long MegaRequest_getPublicNode(long jarg1, MegaRequest jarg1_);
  public final static native long MegaRequest_getPublicMegaNode(long jarg1, MegaRequest jarg1_);
  public final static native int MegaRequest_getParamType(long jarg1, MegaRequest jarg1_);
  public final static native String MegaRequest_getText(long jarg1, MegaRequest jarg1_);
  public final static native long MegaRequest_getNumber(long jarg1, MegaRequest jarg1_);
  public final static native boolean MegaRequest_getFlag(long jarg1, MegaRequest jarg1_);
  public final static native long MegaRequest_getTransferredBytes(long jarg1, MegaRequest jarg1_);
  public final static native long MegaRequest_getTotalBytes(long jarg1, MegaRequest jarg1_);
  public final static native long MegaRequest_getMegaAccountDetails(long jarg1, MegaRequest jarg1_);
  public final static native long MegaRequest_getPricing(long jarg1, MegaRequest jarg1_);
  public final static native int MegaRequest_getTransferTag(long jarg1, MegaRequest jarg1_);
  public final static native int MegaRequest_getNumDetails(long jarg1, MegaRequest jarg1_);
  public final static native void delete_MegaTransfer(long jarg1);
  public final static native long MegaTransfer_copy(long jarg1, MegaTransfer jarg1_);
  public final static native int MegaTransfer_getType(long jarg1, MegaTransfer jarg1_);
  public final static native String MegaTransfer_getTransferString(long jarg1, MegaTransfer jarg1_);
  public final static native String MegaTransfer_toString(long jarg1, MegaTransfer jarg1_);
  public final static native String MegaTransfer___str__(long jarg1, MegaTransfer jarg1_);
  public final static native long MegaTransfer_getStartTime(long jarg1, MegaTransfer jarg1_);
  public final static native long MegaTransfer_getTransferredBytes(long jarg1, MegaTransfer jarg1_);
  public final static native long MegaTransfer_getTotalBytes(long jarg1, MegaTransfer jarg1_);
  public final static native String MegaTransfer_getPath(long jarg1, MegaTransfer jarg1_);
  public final static native String MegaTransfer_getParentPath(long jarg1, MegaTransfer jarg1_);
  public final static native long MegaTransfer_getNodeHandle(long jarg1, MegaTransfer jarg1_);
  public final static native long MegaTransfer_getParentHandle(long jarg1, MegaTransfer jarg1_);
  public final static native long MegaTransfer_getStartPos(long jarg1, MegaTransfer jarg1_);
  public final static native long MegaTransfer_getEndPos(long jarg1, MegaTransfer jarg1_);
  public final static native String MegaTransfer_getFileName(long jarg1, MegaTransfer jarg1_);
  public final static native int MegaTransfer_getNumRetry(long jarg1, MegaTransfer jarg1_);
  public final static native int MegaTransfer_getMaxRetries(long jarg1, MegaTransfer jarg1_);
  public final static native int MegaTransfer_getTag(long jarg1, MegaTransfer jarg1_);
  public final static native long MegaTransfer_getSpeed(long jarg1, MegaTransfer jarg1_);
  public final static native long MegaTransfer_getDeltaSize(long jarg1, MegaTransfer jarg1_);
  public final static native long MegaTransfer_getUpdateTime(long jarg1, MegaTransfer jarg1_);
  public final static native long MegaTransfer_getPublicMegaNode(long jarg1, MegaTransfer jarg1_);
  public final static native boolean MegaTransfer_isSyncTransfer(long jarg1, MegaTransfer jarg1_);
  public final static native boolean MegaTransfer_isStreamingTransfer(long jarg1, MegaTransfer jarg1_);
  public final static native String MegaTransfer_getLastBytes(long jarg1, MegaTransfer jarg1_);
  public final static native long new_MegaError__SWIG_0(int jarg1);
  public final static native long new_MegaError__SWIG_1(long jarg1, MegaError jarg1_);
  public final static native void delete_MegaError(long jarg1);
  public final static native long MegaError_copy(long jarg1, MegaError jarg1_);
  public final static native int MegaError_getErrorCode(long jarg1, MegaError jarg1_);
  public final static native String MegaError_getErrorString__SWIG_0(long jarg1, MegaError jarg1_);
  public final static native String MegaError_toString(long jarg1, MegaError jarg1_);
  public final static native String MegaError___str__(long jarg1, MegaError jarg1_);
  public final static native String MegaError_getErrorString__SWIG_1(int jarg1);
  public final static native boolean MegaTreeProcessor_processMegaNode(long jarg1, MegaTreeProcessor jarg1_, long jarg2, MegaNode jarg2_);
  public final static native boolean MegaTreeProcessor_processMegaNodeSwigExplicitMegaTreeProcessor(long jarg1, MegaTreeProcessor jarg1_, long jarg2, MegaNode jarg2_);
  public final static native void delete_MegaTreeProcessor(long jarg1);
  public final static native long new_MegaTreeProcessor();
  public final static native void MegaTreeProcessor_director_connect(MegaTreeProcessor obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MegaTreeProcessor_change_ownership(MegaTreeProcessor obj, long cptr, boolean take_or_release);
  public final static native void MegaRequestListener_onRequestStart(long jarg1, MegaRequestListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_);
  public final static native void MegaRequestListener_onRequestStartSwigExplicitMegaRequestListener(long jarg1, MegaRequestListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_);
  public final static native void MegaRequestListener_onRequestFinish(long jarg1, MegaRequestListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaRequestListener_onRequestFinishSwigExplicitMegaRequestListener(long jarg1, MegaRequestListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaRequestListener_onRequestUpdate(long jarg1, MegaRequestListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_);
  public final static native void MegaRequestListener_onRequestUpdateSwigExplicitMegaRequestListener(long jarg1, MegaRequestListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_);
  public final static native void MegaRequestListener_onRequestTemporaryError(long jarg1, MegaRequestListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaRequestListener_onRequestTemporaryErrorSwigExplicitMegaRequestListener(long jarg1, MegaRequestListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_, long jarg4, MegaError jarg4_);
  public final static native void delete_MegaRequestListener(long jarg1);
  public final static native long new_MegaRequestListener();
  public final static native void MegaRequestListener_director_connect(MegaRequestListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MegaRequestListener_change_ownership(MegaRequestListener obj, long cptr, boolean take_or_release);
  public final static native void MegaTransferListener_onTransferStart(long jarg1, MegaTransferListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_);
  public final static native void MegaTransferListener_onTransferStartSwigExplicitMegaTransferListener(long jarg1, MegaTransferListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_);
  public final static native void MegaTransferListener_onTransferFinish(long jarg1, MegaTransferListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaTransferListener_onTransferFinishSwigExplicitMegaTransferListener(long jarg1, MegaTransferListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaTransferListener_onTransferUpdate(long jarg1, MegaTransferListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_);
  public final static native void MegaTransferListener_onTransferUpdateSwigExplicitMegaTransferListener(long jarg1, MegaTransferListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_);
  public final static native void MegaTransferListener_onTransferTemporaryError(long jarg1, MegaTransferListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaTransferListener_onTransferTemporaryErrorSwigExplicitMegaTransferListener(long jarg1, MegaTransferListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_, long jarg4, MegaError jarg4_);
  public final static native void delete_MegaTransferListener(long jarg1);
  public final static native boolean MegaTransferListener_onTransferData(long jarg1, MegaTransferListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_, byte[] jarg4);
  public final static native boolean MegaTransferListener_onTransferDataSwigExplicitMegaTransferListener(long jarg1, MegaTransferListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_, byte[] jarg4);
  public final static native long new_MegaTransferListener();
  public final static native void MegaTransferListener_director_connect(MegaTransferListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MegaTransferListener_change_ownership(MegaTransferListener obj, long cptr, boolean take_or_release);
  public final static native void MegaGlobalListener_onUsersUpdate(long jarg1, MegaGlobalListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaUserList jarg3_);
  public final static native void MegaGlobalListener_onUsersUpdateSwigExplicitMegaGlobalListener(long jarg1, MegaGlobalListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaUserList jarg3_);
  public final static native void MegaGlobalListener_onNodesUpdate(long jarg1, MegaGlobalListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaNodeList jarg3_);
  public final static native void MegaGlobalListener_onNodesUpdateSwigExplicitMegaGlobalListener(long jarg1, MegaGlobalListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaNodeList jarg3_);
  public final static native void MegaGlobalListener_onReloadNeeded(long jarg1, MegaGlobalListener jarg1_, long jarg2, MegaApi jarg2_);
  public final static native void MegaGlobalListener_onReloadNeededSwigExplicitMegaGlobalListener(long jarg1, MegaGlobalListener jarg1_, long jarg2, MegaApi jarg2_);
  public final static native void delete_MegaGlobalListener(long jarg1);
  public final static native long new_MegaGlobalListener();
  public final static native void MegaGlobalListener_director_connect(MegaGlobalListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MegaGlobalListener_change_ownership(MegaGlobalListener obj, long cptr, boolean take_or_release);
  public final static native void MegaListener_onRequestStart(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_);
  public final static native void MegaListener_onRequestStartSwigExplicitMegaListener(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_);
  public final static native void MegaListener_onRequestFinish(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaListener_onRequestFinishSwigExplicitMegaListener(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaListener_onRequestUpdate(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_);
  public final static native void MegaListener_onRequestUpdateSwigExplicitMegaListener(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_);
  public final static native void MegaListener_onRequestTemporaryError(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaListener_onRequestTemporaryErrorSwigExplicitMegaListener(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaRequest jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaListener_onTransferStart(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_);
  public final static native void MegaListener_onTransferStartSwigExplicitMegaListener(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_);
  public final static native void MegaListener_onTransferFinish(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaListener_onTransferFinishSwigExplicitMegaListener(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaListener_onTransferUpdate(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_);
  public final static native void MegaListener_onTransferUpdateSwigExplicitMegaListener(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_);
  public final static native void MegaListener_onTransferTemporaryError(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaListener_onTransferTemporaryErrorSwigExplicitMegaListener(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaTransfer jarg3_, long jarg4, MegaError jarg4_);
  public final static native void MegaListener_onUsersUpdate(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaUserList jarg3_);
  public final static native void MegaListener_onUsersUpdateSwigExplicitMegaListener(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaUserList jarg3_);
  public final static native void MegaListener_onNodesUpdate(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaNodeList jarg3_);
  public final static native void MegaListener_onNodesUpdateSwigExplicitMegaListener(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_, long jarg3, MegaNodeList jarg3_);
  public final static native void MegaListener_onReloadNeeded(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_);
  public final static native void MegaListener_onReloadNeededSwigExplicitMegaListener(long jarg1, MegaListener jarg1_, long jarg2, MegaApi jarg2_);
  public final static native void delete_MegaListener(long jarg1);
  public final static native long new_MegaListener();
  public final static native void MegaListener_director_connect(MegaListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MegaListener_change_ownership(MegaListener obj, long cptr, boolean take_or_release);
  public final static native long new_MegaApi__SWIG_0(String jarg1, String jarg2, String jarg3);
  public final static native long new_MegaApi__SWIG_1(String jarg1, String jarg2);
  public final static native long new_MegaApi__SWIG_2(String jarg1);
  public final static native long new_MegaApi__SWIG_3(String jarg1, long jarg2, MegaGfxProcessor jarg2_, String jarg3, String jarg4);
  public final static native long new_MegaApi__SWIG_4(String jarg1, long jarg2, MegaGfxProcessor jarg2_, String jarg3);
  public final static native long new_MegaApi__SWIG_5(String jarg1, long jarg2, MegaGfxProcessor jarg2_);
  public final static native void delete_MegaApi(long jarg1);
  public final static native void MegaApi_addListener(long jarg1, MegaApi jarg1_, long jarg2, MegaListener jarg2_);
  public final static native void MegaApi_addRequestListener(long jarg1, MegaApi jarg1_, long jarg2, MegaRequestListener jarg2_);
  public final static native void MegaApi_addTransferListener(long jarg1, MegaApi jarg1_, long jarg2, MegaTransferListener jarg2_);
  public final static native void MegaApi_addGlobalListener(long jarg1, MegaApi jarg1_, long jarg2, MegaGlobalListener jarg2_);
  public final static native void MegaApi_removeListener(long jarg1, MegaApi jarg1_, long jarg2, MegaListener jarg2_);
  public final static native void MegaApi_removeRequestListener(long jarg1, MegaApi jarg1_, long jarg2, MegaRequestListener jarg2_);
  public final static native void MegaApi_removeTransferListener(long jarg1, MegaApi jarg1_, long jarg2, MegaTransferListener jarg2_);
  public final static native void MegaApi_removeGlobalListener(long jarg1, MegaApi jarg1_, long jarg2, MegaGlobalListener jarg2_);
  public final static native String MegaApi_getBase64PwKey(long jarg1, MegaApi jarg1_, String jarg2);
  public final static native String MegaApi_getStringHash(long jarg1, MegaApi jarg1_, String jarg2, String jarg3);
  public final static native long MegaApi_base64ToHandle(String jarg1);
  public final static native String MegaApi_handleToBase64(long jarg1);
  public final static native void MegaApi_addEntropy(String jarg1, long jarg2);
  public final static native void MegaApi_retryPendingConnections__SWIG_0(long jarg1, MegaApi jarg1_, boolean jarg2, boolean jarg3, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_retryPendingConnections__SWIG_1(long jarg1, MegaApi jarg1_, boolean jarg2, boolean jarg3);
  public final static native void MegaApi_retryPendingConnections__SWIG_2(long jarg1, MegaApi jarg1_, boolean jarg2);
  public final static native void MegaApi_retryPendingConnections__SWIG_3(long jarg1, MegaApi jarg1_);
  public final static native void MegaApi_login__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, String jarg3, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_login__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2, String jarg3);
  public final static native void MegaApi_loginToFolder__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_loginToFolder__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2);
  public final static native void MegaApi_fastLogin__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, String jarg3, String jarg4, long jarg5, MegaRequestListener jarg5_);
  public final static native void MegaApi_fastLogin__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native void MegaApi_fastLogin__SWIG_2(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_fastLogin__SWIG_3(long jarg1, MegaApi jarg1_, String jarg2);
  public final static native String MegaApi_dumpSession(long jarg1, MegaApi jarg1_);
  public final static native void MegaApi_createAccount__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, String jarg3, String jarg4, long jarg5, MegaRequestListener jarg5_);
  public final static native void MegaApi_createAccount__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native void MegaApi_fastCreateAccount__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, String jarg3, String jarg4, long jarg5, MegaRequestListener jarg5_);
  public final static native void MegaApi_fastCreateAccount__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native void MegaApi_querySignupLink__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_querySignupLink__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2);
  public final static native void MegaApi_confirmAccount__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, String jarg3, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_confirmAccount__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2, String jarg3);
  public final static native void MegaApi_fastConfirmAccount__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, String jarg3, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_fastConfirmAccount__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2, String jarg3);
  public final static native void MegaApi_setProxySettings(long jarg1, MegaApi jarg1_, long jarg2, MegaProxy jarg2_);
  public final static native long MegaApi_getAutoProxySettings(long jarg1, MegaApi jarg1_);
  public final static native int MegaApi_isLoggedIn(long jarg1, MegaApi jarg1_);
  public final static native String MegaApi_getMyEmail(long jarg1, MegaApi jarg1_);
  public final static native void MegaApi_setLogLevel(int jarg1);
  public final static native void MegaApi_setLoggerObject(long jarg1, MegaLogger jarg1_);
  public final static native void MegaApi_log__SWIG_0(int jarg1, String jarg2, String jarg3, int jarg4);
  public final static native void MegaApi_log__SWIG_1(int jarg1, String jarg2, String jarg3);
  public final static native void MegaApi_log__SWIG_2(int jarg1, String jarg2);
  public final static native void MegaApi_createFolder__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaNode jarg3_, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_createFolder__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaNode jarg3_);
  public final static native void MegaApi_moveNode__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaNode jarg3_, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_moveNode__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaNode jarg3_);
  public final static native void MegaApi_copyNode__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaNode jarg3_, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_copyNode__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaNode jarg3_);
  public final static native void MegaApi_renameNode__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_renameNode__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3);
  public final static native void MegaApi_remove__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_remove__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native void MegaApi_sendFileToUser__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaUser jarg3_, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_sendFileToUser__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaUser jarg3_);
  public final static native void MegaApi_share__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaUser jarg3_, int jarg4, long jarg5, MegaRequestListener jarg5_);
  public final static native void MegaApi_share__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaUser jarg3_, int jarg4);
  public final static native void MegaApi_importFileLink__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaNode jarg3_, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_importFileLink__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaNode jarg3_);
  public final static native void MegaApi_getPublicNode__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_getPublicNode__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2);
  public final static native void MegaApi_getThumbnail__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_getThumbnail__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3);
  public final static native void MegaApi_getPreview__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_getPreview__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3);
  public final static native void MegaApi_getUserAvatar__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaUser jarg2_, String jarg3, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_getUserAvatar__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaUser jarg2_, String jarg3);
  public final static native void MegaApi_cancelGetThumbnail__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_cancelGetThumbnail__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native void MegaApi_cancelGetPreview__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_cancelGetPreview__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native void MegaApi_setThumbnail__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_setThumbnail__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3);
  public final static native void MegaApi_setPreview__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_setPreview__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3);
  public final static native void MegaApi_setAvatar__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_setAvatar__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2);
  public final static native void MegaApi_exportNode__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_exportNode__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native void MegaApi_disableExport__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_disableExport__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native void MegaApi_fetchNodes__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaRequestListener jarg2_);
  public final static native void MegaApi_fetchNodes__SWIG_1(long jarg1, MegaApi jarg1_);
  public final static native void MegaApi_getAccountDetails__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaRequestListener jarg2_);
  public final static native void MegaApi_getAccountDetails__SWIG_1(long jarg1, MegaApi jarg1_);
  public final static native void MegaApi_getPricing__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaRequestListener jarg2_);
  public final static native void MegaApi_getPricing__SWIG_1(long jarg1, MegaApi jarg1_);
  public final static native void MegaApi_getPaymentUrl__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_getPaymentUrl__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2);
  public final static native String MegaApi_exportMasterKey(long jarg1, MegaApi jarg1_);
  public final static native void MegaApi_changePassword__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, String jarg3, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_changePassword__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2, String jarg3);
  public final static native void MegaApi_addContact__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_addContact__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2);
  public final static native void MegaApi_removeContact__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaUser jarg2_, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_removeContact__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaUser jarg2_);
  public final static native void MegaApi_logout__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaRequestListener jarg2_);
  public final static native void MegaApi_logout__SWIG_1(long jarg1, MegaApi jarg1_);
  public final static native void MegaApi_submitFeedback__SWIG_0(long jarg1, MegaApi jarg1_, int jarg2, String jarg3, long jarg4, MegaRequestListener jarg4_);
  public final static native void MegaApi_submitFeedback__SWIG_1(long jarg1, MegaApi jarg1_, int jarg2, String jarg3);
  public final static native void MegaApi_reportDebugEvent__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_reportDebugEvent__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2);
  public final static native void MegaApi_startUpload__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaNode jarg3_, long jarg4, MegaTransferListener jarg4_);
  public final static native void MegaApi_startUpload__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaNode jarg3_);
  public final static native void MegaApi_startUpload__SWIG_2(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaNode jarg3_, long jarg4, long jarg5, MegaTransferListener jarg5_);
  public final static native void MegaApi_startUpload__SWIG_3(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaNode jarg3_, long jarg4);
  public final static native void MegaApi_startUpload__SWIG_4(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaNode jarg3_, String jarg4, long jarg5, MegaTransferListener jarg5_);
  public final static native void MegaApi_startUpload__SWIG_5(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaNode jarg3_, String jarg4);
  public final static native void MegaApi_startUpload__SWIG_6(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaNode jarg3_, String jarg4, long jarg5, long jarg6, MegaTransferListener jarg6_);
  public final static native void MegaApi_startUpload__SWIG_7(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaNode jarg3_, String jarg4, long jarg5);
  public final static native void MegaApi_startDownload__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3, long jarg4, MegaTransferListener jarg4_);
  public final static native void MegaApi_startDownload__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3);
  public final static native void MegaApi_startStreaming(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, long jarg4, long jarg5, MegaTransferListener jarg5_);
  public final static native void MegaApi_cancelTransfer__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaTransfer jarg2_, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_cancelTransfer__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaTransfer jarg2_);
  public final static native void MegaApi_cancelTransfers__SWIG_0(long jarg1, MegaApi jarg1_, int jarg2, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_cancelTransfers__SWIG_1(long jarg1, MegaApi jarg1_, int jarg2);
  public final static native void MegaApi_pauseTransfers__SWIG_0(long jarg1, MegaApi jarg1_, boolean jarg2, long jarg3, MegaRequestListener jarg3_);
  public final static native void MegaApi_pauseTransfers__SWIG_1(long jarg1, MegaApi jarg1_, boolean jarg2);
  public final static native void MegaApi_setUploadLimit(long jarg1, MegaApi jarg1_, int jarg2);
  public final static native long MegaApi_getTransfers(long jarg1, MegaApi jarg1_);
  public final static native void MegaApi_update(long jarg1, MegaApi jarg1_);
  public final static native boolean MegaApi_isWaiting(long jarg1, MegaApi jarg1_);
  public final static native int MegaApi_getNumPendingUploads(long jarg1, MegaApi jarg1_);
  public final static native int MegaApi_getNumPendingDownloads(long jarg1, MegaApi jarg1_);
  public final static native int MegaApi_getTotalUploads(long jarg1, MegaApi jarg1_);
  public final static native int MegaApi_getTotalDownloads(long jarg1, MegaApi jarg1_);
  public final static native void MegaApi_resetTotalDownloads(long jarg1, MegaApi jarg1_);
  public final static native void MegaApi_resetTotalUploads(long jarg1, MegaApi jarg1_);
  public final static native long MegaApi_getTotalDownloadedBytes(long jarg1, MegaApi jarg1_);
  public final static native long MegaApi_getTotalUploadedBytes(long jarg1, MegaApi jarg1_);
  public final static native void MegaApi_updateStats(long jarg1, MegaApi jarg1_);
  public final static native int MegaApi_getNumChildren(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native int MegaApi_getNumChildFiles(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native int MegaApi_getNumChildFolders(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native long MegaApi_getChildren__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, int jarg3);
  public final static native long MegaApi_getChildren__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native int MegaApi_getIndex__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, int jarg3);
  public final static native int MegaApi_getIndex__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native long MegaApi_getChildNode(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3);
  public final static native long MegaApi_getParentNode(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native String MegaApi_getNodePath(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native long MegaApi_getNodeByPath__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2, long jarg3, MegaNode jarg3_);
  public final static native long MegaApi_getNodeByPath__SWIG_1(long jarg1, MegaApi jarg1_, String jarg2);
  public final static native long MegaApi_getNodeByHandle(long jarg1, MegaApi jarg1_, long jarg2);
  public final static native long MegaApi_getContacts(long jarg1, MegaApi jarg1_);
  public final static native long MegaApi_getContact(long jarg1, MegaApi jarg1_, String jarg2);
  public final static native long MegaApi_getInShares__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaUser jarg2_);
  public final static native long MegaApi_getInShares__SWIG_1(long jarg1, MegaApi jarg1_);
  public final static native boolean MegaApi_isShared(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native long MegaApi_getOutShares__SWIG_0(long jarg1, MegaApi jarg1_);
  public final static native long MegaApi_getOutShares__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native int MegaApi_getAccess(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native long MegaApi_getSize(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native String MegaApi_getFingerprint__SWIG_0(long jarg1, MegaApi jarg1_, String jarg2);
  public final static native String MegaApi_getFingerprint__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_);
  public final static native long MegaApi_getNodeByFingerprint(long jarg1, MegaApi jarg1_, String jarg2);
  public final static native boolean MegaApi_hasFingerprint(long jarg1, MegaApi jarg1_, String jarg2);
  public final static native long MegaApi_checkAccess(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, int jarg3);
  public final static native long MegaApi_checkMove(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaNode jarg3_);
  public final static native long MegaApi_getRootNode(long jarg1, MegaApi jarg1_);
  public final static native long MegaApi_getInboxNode(long jarg1, MegaApi jarg1_);
  public final static native long MegaApi_getRubbishNode(long jarg1, MegaApi jarg1_);
  public final static native long MegaApi_search__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3, boolean jarg4);
  public final static native long MegaApi_search__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, String jarg3);
  public final static native boolean MegaApi_processMegaTree__SWIG_0(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaTreeProcessor jarg3_, boolean jarg4);
  public final static native boolean MegaApi_processMegaTree__SWIG_1(long jarg1, MegaApi jarg1_, long jarg2, MegaNode jarg2_, long jarg3, MegaTreeProcessor jarg3_);
  public final static native String MegaApi_strdup(String jarg1);
  public final static native void MegaApi_removeRecursively(String jarg1);
  public final static native void delete_MegaAccountDetails(long jarg1);
  public final static native int MegaAccountDetails_getProLevel(long jarg1, MegaAccountDetails jarg1_);
  public final static native long MegaAccountDetails_getStorageMax(long jarg1, MegaAccountDetails jarg1_);
  public final static native long MegaAccountDetails_getStorageUsed__SWIG_0(long jarg1, MegaAccountDetails jarg1_);
  public final static native long MegaAccountDetails_getTransferMax(long jarg1, MegaAccountDetails jarg1_);
  public final static native long MegaAccountDetails_getTransferOwnUsed(long jarg1, MegaAccountDetails jarg1_);
  public final static native long MegaAccountDetails_getStorageUsed__SWIG_1(long jarg1, MegaAccountDetails jarg1_, long jarg2);
  public final static native long MegaAccountDetails_getNumFiles(long jarg1, MegaAccountDetails jarg1_, long jarg2);
  public final static native long MegaAccountDetails_getNumFolders(long jarg1, MegaAccountDetails jarg1_, long jarg2);
  public final static native long MegaAccountDetails_copy(long jarg1, MegaAccountDetails jarg1_);
  public final static native void delete_MegaPricing(long jarg1);
  public final static native int MegaPricing_getNumProducts(long jarg1, MegaPricing jarg1_);
  public final static native long MegaPricing_getHandle(long jarg1, MegaPricing jarg1_, int jarg2);
  public final static native int MegaPricing_getProLevel(long jarg1, MegaPricing jarg1_, int jarg2);
  public final static native int MegaPricing_getGBStorage(long jarg1, MegaPricing jarg1_, int jarg2);
  public final static native int MegaPricing_getGBTransfer(long jarg1, MegaPricing jarg1_, int jarg2);
  public final static native int MegaPricing_getMonths(long jarg1, MegaPricing jarg1_, int jarg2);
  public final static native int MegaPricing_getAmount(long jarg1, MegaPricing jarg1_, int jarg2);
  public final static native String MegaPricing_getCurrency(long jarg1, MegaPricing jarg1_, int jarg2);
  public final static native long MegaPricing_copy(long jarg1, MegaPricing jarg1_);

  public static boolean SwigDirector_MegaGfxProcessor_readBitmap(MegaGfxProcessor self, String path) {
    return self.readBitmap(path);
  }
  public static int SwigDirector_MegaGfxProcessor_getWidth(MegaGfxProcessor self) {
    return self.getWidth();
  }
  public static int SwigDirector_MegaGfxProcessor_getHeight(MegaGfxProcessor self) {
    return self.getHeight();
  }
  public static int SwigDirector_MegaGfxProcessor_getBitmapDataSize(MegaGfxProcessor self, int width, int height, int px, int py, int rw, int rh) {
    return self.getBitmapDataSize(width, height, px, py, rw, rh);
  }
  public static boolean SwigDirector_MegaGfxProcessor_getBitmapData(MegaGfxProcessor self, byte[] bitmapData) {
    return self.getBitmapData(bitmapData);
  }
  public static void SwigDirector_MegaGfxProcessor_freeBitmap(MegaGfxProcessor self) {
    self.freeBitmap();
  }
  public static void SwigDirector_MegaLogger_log(MegaLogger self, String time, int loglevel, String source, String message) {
    self.log(time, loglevel, source, message);
  }
  public static boolean SwigDirector_MegaTreeProcessor_processMegaNode(MegaTreeProcessor self, long node) {
    return self.processMegaNode((node == 0) ? null : new MegaNode(node, false));
  }
  public static void SwigDirector_MegaRequestListener_onRequestStart(MegaRequestListener self, long api, long request) {
    self.onRequestStart((api == 0) ? null : new MegaApi(api, false), (request == 0) ? null : new MegaRequest(request, false));
  }
  public static void SwigDirector_MegaRequestListener_onRequestFinish(MegaRequestListener self, long api, long request, long e) {
    self.onRequestFinish((api == 0) ? null : new MegaApi(api, false), (request == 0) ? null : new MegaRequest(request, false), (e == 0) ? null : new MegaError(e, false));
  }
  public static void SwigDirector_MegaRequestListener_onRequestUpdate(MegaRequestListener self, long api, long request) {
    self.onRequestUpdate((api == 0) ? null : new MegaApi(api, false), (request == 0) ? null : new MegaRequest(request, false));
  }
  public static void SwigDirector_MegaRequestListener_onRequestTemporaryError(MegaRequestListener self, long api, long request, long error) {
    self.onRequestTemporaryError((api == 0) ? null : new MegaApi(api, false), (request == 0) ? null : new MegaRequest(request, false), (error == 0) ? null : new MegaError(error, false));
  }
  public static void SwigDirector_MegaTransferListener_onTransferStart(MegaTransferListener self, long api, long transfer) {
    self.onTransferStart((api == 0) ? null : new MegaApi(api, false), (transfer == 0) ? null : new MegaTransfer(transfer, false));
  }
  public static void SwigDirector_MegaTransferListener_onTransferFinish(MegaTransferListener self, long api, long transfer, long error) {
    self.onTransferFinish((api == 0) ? null : new MegaApi(api, false), (transfer == 0) ? null : new MegaTransfer(transfer, false), (error == 0) ? null : new MegaError(error, false));
  }
  public static void SwigDirector_MegaTransferListener_onTransferUpdate(MegaTransferListener self, long api, long transfer) {
    self.onTransferUpdate((api == 0) ? null : new MegaApi(api, false), (transfer == 0) ? null : new MegaTransfer(transfer, false));
  }
  public static void SwigDirector_MegaTransferListener_onTransferTemporaryError(MegaTransferListener self, long api, long transfer, long error) {
    self.onTransferTemporaryError((api == 0) ? null : new MegaApi(api, false), (transfer == 0) ? null : new MegaTransfer(transfer, false), (error == 0) ? null : new MegaError(error, false));
  }
  public static boolean SwigDirector_MegaTransferListener_onTransferData(MegaTransferListener self, long api, long transfer, byte[] buffer) {
    return self.onTransferData((api == 0) ? null : new MegaApi(api, false), (transfer == 0) ? null : new MegaTransfer(transfer, false), buffer);
  }
  public static void SwigDirector_MegaGlobalListener_onUsersUpdate(MegaGlobalListener self, long api, long users) {
    self.onUsersUpdate((api == 0) ? null : new MegaApi(api, false), (users == 0) ? null : new MegaUserList(users, false));
  }
  public static void SwigDirector_MegaGlobalListener_onNodesUpdate(MegaGlobalListener self, long api, long nodes) {
    self.onNodesUpdate((api == 0) ? null : new MegaApi(api, false), (nodes == 0) ? null : new MegaNodeList(nodes, false));
  }
  public static void SwigDirector_MegaGlobalListener_onReloadNeeded(MegaGlobalListener self, long api) {
    self.onReloadNeeded((api == 0) ? null : new MegaApi(api, false));
  }
  public static void SwigDirector_MegaListener_onRequestStart(MegaListener self, long api, long request) {
    self.onRequestStart((api == 0) ? null : new MegaApi(api, false), (request == 0) ? null : new MegaRequest(request, false));
  }
  public static void SwigDirector_MegaListener_onRequestFinish(MegaListener self, long api, long request, long e) {
    self.onRequestFinish((api == 0) ? null : new MegaApi(api, false), (request == 0) ? null : new MegaRequest(request, false), (e == 0) ? null : new MegaError(e, false));
  }
  public static void SwigDirector_MegaListener_onRequestUpdate(MegaListener self, long api, long request) {
    self.onRequestUpdate((api == 0) ? null : new MegaApi(api, false), (request == 0) ? null : new MegaRequest(request, false));
  }
  public static void SwigDirector_MegaListener_onRequestTemporaryError(MegaListener self, long api, long request, long error) {
    self.onRequestTemporaryError((api == 0) ? null : new MegaApi(api, false), (request == 0) ? null : new MegaRequest(request, false), (error == 0) ? null : new MegaError(error, false));
  }
  public static void SwigDirector_MegaListener_onTransferStart(MegaListener self, long api, long transfer) {
    self.onTransferStart((api == 0) ? null : new MegaApi(api, false), (transfer == 0) ? null : new MegaTransfer(transfer, false));
  }
  public static void SwigDirector_MegaListener_onTransferFinish(MegaListener self, long api, long transfer, long error) {
    self.onTransferFinish((api == 0) ? null : new MegaApi(api, false), (transfer == 0) ? null : new MegaTransfer(transfer, false), (error == 0) ? null : new MegaError(error, false));
  }
  public static void SwigDirector_MegaListener_onTransferUpdate(MegaListener self, long api, long transfer) {
    self.onTransferUpdate((api == 0) ? null : new MegaApi(api, false), (transfer == 0) ? null : new MegaTransfer(transfer, false));
  }
  public static void SwigDirector_MegaListener_onTransferTemporaryError(MegaListener self, long api, long transfer, long error) {
    self.onTransferTemporaryError((api == 0) ? null : new MegaApi(api, false), (transfer == 0) ? null : new MegaTransfer(transfer, false), (error == 0) ? null : new MegaError(error, false));
  }
  public static void SwigDirector_MegaListener_onUsersUpdate(MegaListener self, long api, long users) {
    self.onUsersUpdate((api == 0) ? null : new MegaApi(api, false), (users == 0) ? null : new MegaUserList(users, false));
  }
  public static void SwigDirector_MegaListener_onNodesUpdate(MegaListener self, long api, long nodes) {
    self.onNodesUpdate((api == 0) ? null : new MegaApi(api, false), (nodes == 0) ? null : new MegaNodeList(nodes, false));
  }
  public static void SwigDirector_MegaListener_onReloadNeeded(MegaListener self, long api) {
    self.onReloadNeeded((api == 0) ? null : new MegaApi(api, false));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
