/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaProxy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MegaProxy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaProxy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaProxy(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public MegaProxy() {
    this(megaJNI.new_MegaProxy(), true);
  }

  public void setProxyType(int proxyType) {
    megaJNI.MegaProxy_setProxyType(swigCPtr, this, proxyType);
  }

  public void setProxyURL(String proxyURL) {
    megaJNI.MegaProxy_setProxyURL(swigCPtr, this, proxyURL);
  }

  public void setCredentials(String username, String password) {
    megaJNI.MegaProxy_setCredentials(swigCPtr, this, username, password);
  }

  public int getProxyType() {
    return megaJNI.MegaProxy_getProxyType(swigCPtr, this);
  }

  public String getProxyURL() {
    return megaJNI.MegaProxy_getProxyURL(swigCPtr, this);
  }

  public boolean credentialsNeeded() {
    return megaJNI.MegaProxy_credentialsNeeded(swigCPtr, this);
  }

  public String getUsername() {
    return megaJNI.MegaProxy_getUsername(swigCPtr, this);
  }

  public String getPassword() {
    return megaJNI.MegaProxy_getPassword(swigCPtr, this);
  }

  public final static int PROXY_NONE = 0;
  public final static int PROXY_AUTO = 1;
  public final static int PROXY_CUSTOM = 2;

}
