/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaAccountTransaction {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MegaAccountTransaction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaAccountTransaction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaAccountTransaction(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public long getTimestamp() {
    return megaJNI.MegaAccountTransaction_getTimestamp(swigCPtr, this);
  }

  public String getHandle() {
    return megaJNI.MegaAccountTransaction_getHandle(swigCPtr, this);
  }

  public String getCurrency() {
    return megaJNI.MegaAccountTransaction_getCurrency(swigCPtr, this);
  }

  public double getAmount() {
    return megaJNI.MegaAccountTransaction_getAmount(swigCPtr, this);
  }

  public MegaAccountTransaction() {
    this(megaJNI.new_MegaAccountTransaction(), true);
  }

}
