/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

class MegaApi {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MegaApi(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaApi obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaApi(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public MegaApi(String appKey, String basePath, String userAgent) {
    this(megaJNI.new_MegaApi__SWIG_0(appKey, basePath, userAgent), true);
  }

  public MegaApi(String appKey, String basePath) {
    this(megaJNI.new_MegaApi__SWIG_1(appKey, basePath), true);
  }

  public MegaApi(String appKey) {
    this(megaJNI.new_MegaApi__SWIG_2(appKey), true);
  }

  public MegaApi(String appKey, MegaGfxProcessor processor, String basePath, String userAgent) {
    this(megaJNI.new_MegaApi__SWIG_3(appKey, MegaGfxProcessor.getCPtr(processor), processor, basePath, userAgent), true);
  }

  public MegaApi(String appKey, MegaGfxProcessor processor, String basePath) {
    this(megaJNI.new_MegaApi__SWIG_4(appKey, MegaGfxProcessor.getCPtr(processor), processor, basePath), true);
  }

  public MegaApi(String appKey, MegaGfxProcessor processor) {
    this(megaJNI.new_MegaApi__SWIG_5(appKey, MegaGfxProcessor.getCPtr(processor), processor), true);
  }

  public void addListener(MegaListener listener) {
    megaJNI.MegaApi_addListener(swigCPtr, this, MegaListener.getCPtr(listener), listener);
  }

  public void addRequestListener(MegaRequestListener listener) {
    megaJNI.MegaApi_addRequestListener(swigCPtr, this, MegaRequestListener.getCPtr(listener), listener);
  }

  public void addTransferListener(MegaTransferListener listener) {
    megaJNI.MegaApi_addTransferListener(swigCPtr, this, MegaTransferListener.getCPtr(listener), listener);
  }

  public void addGlobalListener(MegaGlobalListener listener) {
    megaJNI.MegaApi_addGlobalListener(swigCPtr, this, MegaGlobalListener.getCPtr(listener), listener);
  }

  public void removeListener(MegaListener listener) {
    megaJNI.MegaApi_removeListener(swigCPtr, this, MegaListener.getCPtr(listener), listener);
  }

  public void removeRequestListener(MegaRequestListener listener) {
    megaJNI.MegaApi_removeRequestListener(swigCPtr, this, MegaRequestListener.getCPtr(listener), listener);
  }

  public void removeTransferListener(MegaTransferListener listener) {
    megaJNI.MegaApi_removeTransferListener(swigCPtr, this, MegaTransferListener.getCPtr(listener), listener);
  }

  public void removeGlobalListener(MegaGlobalListener listener) {
    megaJNI.MegaApi_removeGlobalListener(swigCPtr, this, MegaGlobalListener.getCPtr(listener), listener);
  }

  public MegaRequest getCurrentRequest() {
    long cPtr = megaJNI.MegaApi_getCurrentRequest(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaRequest(cPtr, false);
  }

  public MegaTransfer getCurrentTransfer() {
    long cPtr = megaJNI.MegaApi_getCurrentTransfer(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaTransfer(cPtr, false);
  }

  public MegaError getCurrentError() {
    long cPtr = megaJNI.MegaApi_getCurrentError(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaError(cPtr, false);
  }

  public MegaNodeList getCurrentNodes() {
    long cPtr = megaJNI.MegaApi_getCurrentNodes(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNodeList(cPtr, false);
  }

  public MegaUserList getCurrentUsers() {
    long cPtr = megaJNI.MegaApi_getCurrentUsers(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaUserList(cPtr, false);
  }

  public String getBase64PwKey(String password) {
    return megaJNI.MegaApi_getBase64PwKey(swigCPtr, this, password);
  }

  public String getStringHash(String base64pwkey, String email) {
    return megaJNI.MegaApi_getStringHash(swigCPtr, this, base64pwkey, email);
  }

  public void getSessionTransferURL(String path, MegaRequestListener listener) {
    megaJNI.MegaApi_getSessionTransferURL__SWIG_0(swigCPtr, this, path, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getSessionTransferURL(String path) {
    megaJNI.MegaApi_getSessionTransferURL__SWIG_1(swigCPtr, this, path);
  }

  public static long base32ToHandle(String base32Handle) {
    return megaJNI.MegaApi_base32ToHandle(base32Handle);
  }

  public static long base64ToHandle(String base64Handle) {
    return megaJNI.MegaApi_base64ToHandle(base64Handle);
  }

  public static String handleToBase64(long handle) {
    return megaJNI.MegaApi_handleToBase64(handle);
  }

  public static String userHandleToBase64(long handle) {
    return megaJNI.MegaApi_userHandleToBase64(handle);
  }

  public static void addEntropy(String data, long size) {
    megaJNI.MegaApi_addEntropy(data, size);
  }

  public void retryPendingConnections(boolean disconnect, boolean includexfers, MegaRequestListener listener) {
    megaJNI.MegaApi_retryPendingConnections__SWIG_0(swigCPtr, this, disconnect, includexfers, MegaRequestListener.getCPtr(listener), listener);
  }

  public void retryPendingConnections(boolean disconnect, boolean includexfers) {
    megaJNI.MegaApi_retryPendingConnections__SWIG_1(swigCPtr, this, disconnect, includexfers);
  }

  public void retryPendingConnections(boolean disconnect) {
    megaJNI.MegaApi_retryPendingConnections__SWIG_2(swigCPtr, this, disconnect);
  }

  public void retryPendingConnections() {
    megaJNI.MegaApi_retryPendingConnections__SWIG_3(swigCPtr, this);
  }

  public void login(String email, String password, MegaRequestListener listener) {
    megaJNI.MegaApi_login__SWIG_0(swigCPtr, this, email, password, MegaRequestListener.getCPtr(listener), listener);
  }

  public void login(String email, String password) {
    megaJNI.MegaApi_login__SWIG_1(swigCPtr, this, email, password);
  }

  public void loginToFolder(String megaFolderLink, MegaRequestListener listener) {
    megaJNI.MegaApi_loginToFolder__SWIG_0(swigCPtr, this, megaFolderLink, MegaRequestListener.getCPtr(listener), listener);
  }

  public void loginToFolder(String megaFolderLink) {
    megaJNI.MegaApi_loginToFolder__SWIG_1(swigCPtr, this, megaFolderLink);
  }

  public void fastLogin(String email, String stringHash, String base64pwkey, MegaRequestListener listener) {
    megaJNI.MegaApi_fastLogin__SWIG_0(swigCPtr, this, email, stringHash, base64pwkey, MegaRequestListener.getCPtr(listener), listener);
  }

  public void fastLogin(String email, String stringHash, String base64pwkey) {
    megaJNI.MegaApi_fastLogin__SWIG_1(swigCPtr, this, email, stringHash, base64pwkey);
  }

  public void fastLogin(String session, MegaRequestListener listener) {
    megaJNI.MegaApi_fastLogin__SWIG_2(swigCPtr, this, session, MegaRequestListener.getCPtr(listener), listener);
  }

  public void fastLogin(String session) {
    megaJNI.MegaApi_fastLogin__SWIG_3(swigCPtr, this, session);
  }

  public void killSession(long sessionHandle, MegaRequestListener listener) {
    megaJNI.MegaApi_killSession__SWIG_0(swigCPtr, this, sessionHandle, MegaRequestListener.getCPtr(listener), listener);
  }

  public void killSession(long sessionHandle) {
    megaJNI.MegaApi_killSession__SWIG_1(swigCPtr, this, sessionHandle);
  }

  public void getUserData(MegaRequestListener listener) {
    megaJNI.MegaApi_getUserData__SWIG_0(swigCPtr, this, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getUserData() {
    megaJNI.MegaApi_getUserData__SWIG_1(swigCPtr, this);
  }

  public void getUserData(MegaUser user, MegaRequestListener listener) {
    megaJNI.MegaApi_getUserData__SWIG_2(swigCPtr, this, MegaUser.getCPtr(user), user, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getUserData(MegaUser user) {
    megaJNI.MegaApi_getUserData__SWIG_3(swigCPtr, this, MegaUser.getCPtr(user), user);
  }

  public void getUserData(String user, MegaRequestListener listener) {
    megaJNI.MegaApi_getUserData__SWIG_4(swigCPtr, this, user, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getUserData(String user) {
    megaJNI.MegaApi_getUserData__SWIG_5(swigCPtr, this, user);
  }

  public String dumpSession() {
    return megaJNI.MegaApi_dumpSession(swigCPtr, this);
  }

  public String dumpXMPPSession() {
    return megaJNI.MegaApi_dumpXMPPSession(swigCPtr, this);
  }

  public void createAccount(String email, String password, String name, MegaRequestListener listener) {
    megaJNI.MegaApi_createAccount__SWIG_0(swigCPtr, this, email, password, name, MegaRequestListener.getCPtr(listener), listener);
  }

  public void createAccount(String email, String password, String name) {
    megaJNI.MegaApi_createAccount__SWIG_1(swigCPtr, this, email, password, name);
  }

  public void createAccount(String email, String password, String firstname, String lastname, MegaRequestListener listener) {
    megaJNI.MegaApi_createAccount__SWIG_2(swigCPtr, this, email, password, firstname, lastname, MegaRequestListener.getCPtr(listener), listener);
  }

  public void createAccount(String email, String password, String firstname, String lastname) {
    megaJNI.MegaApi_createAccount__SWIG_3(swigCPtr, this, email, password, firstname, lastname);
  }

  public void fastCreateAccount(String email, String base64pwkey, String name, MegaRequestListener listener) {
    megaJNI.MegaApi_fastCreateAccount__SWIG_0(swigCPtr, this, email, base64pwkey, name, MegaRequestListener.getCPtr(listener), listener);
  }

  public void fastCreateAccount(String email, String base64pwkey, String name) {
    megaJNI.MegaApi_fastCreateAccount__SWIG_1(swigCPtr, this, email, base64pwkey, name);
  }

  public void querySignupLink(String link, MegaRequestListener listener) {
    megaJNI.MegaApi_querySignupLink__SWIG_0(swigCPtr, this, link, MegaRequestListener.getCPtr(listener), listener);
  }

  public void querySignupLink(String link) {
    megaJNI.MegaApi_querySignupLink__SWIG_1(swigCPtr, this, link);
  }

  public void confirmAccount(String link, String password, MegaRequestListener listener) {
    megaJNI.MegaApi_confirmAccount__SWIG_0(swigCPtr, this, link, password, MegaRequestListener.getCPtr(listener), listener);
  }

  public void confirmAccount(String link, String password) {
    megaJNI.MegaApi_confirmAccount__SWIG_1(swigCPtr, this, link, password);
  }

  public void fastConfirmAccount(String link, String base64pwkey, MegaRequestListener listener) {
    megaJNI.MegaApi_fastConfirmAccount__SWIG_0(swigCPtr, this, link, base64pwkey, MegaRequestListener.getCPtr(listener), listener);
  }

  public void fastConfirmAccount(String link, String base64pwkey) {
    megaJNI.MegaApi_fastConfirmAccount__SWIG_1(swigCPtr, this, link, base64pwkey);
  }

  public void setProxySettings(MegaProxy proxySettings) {
    megaJNI.MegaApi_setProxySettings(swigCPtr, this, MegaProxy.getCPtr(proxySettings), proxySettings);
  }

  public MegaProxy getAutoProxySettings() {
    long cPtr = megaJNI.MegaApi_getAutoProxySettings(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaProxy(cPtr, false);
  }

  public int isLoggedIn() {
    return megaJNI.MegaApi_isLoggedIn(swigCPtr, this);
  }

  public String getMyEmail() {
    return megaJNI.MegaApi_getMyEmail(swigCPtr, this);
  }

  public String getMyUserHandle() {
    return megaJNI.MegaApi_getMyUserHandle(swigCPtr, this);
  }

  public String getMyXMPPJid() {
    return megaJNI.MegaApi_getMyXMPPJid(swigCPtr, this);
  }

  public static void setLogLevel(int logLevel) {
    megaJNI.MegaApi_setLogLevel(logLevel);
  }

  public static void setLoggerObject(MegaLogger megaLogger) {
    megaJNI.MegaApi_setLoggerObject(MegaLogger.getCPtr(megaLogger), megaLogger);
  }

  public static void log(int logLevel, String message, String filename, int line) {
    megaJNI.MegaApi_log__SWIG_0(logLevel, message, filename, line);
  }

  public static void log(int logLevel, String message, String filename) {
    megaJNI.MegaApi_log__SWIG_1(logLevel, message, filename);
  }

  public static void log(int logLevel, String message) {
    megaJNI.MegaApi_log__SWIG_2(logLevel, message);
  }

  public void createFolder(String name, MegaNode parent, MegaRequestListener listener) {
    megaJNI.MegaApi_createFolder__SWIG_0(swigCPtr, this, name, MegaNode.getCPtr(parent), parent, MegaRequestListener.getCPtr(listener), listener);
  }

  public void createFolder(String name, MegaNode parent) {
    megaJNI.MegaApi_createFolder__SWIG_1(swigCPtr, this, name, MegaNode.getCPtr(parent), parent);
  }

  public void moveNode(MegaNode node, MegaNode newParent, MegaRequestListener listener) {
    megaJNI.MegaApi_moveNode__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, MegaNode.getCPtr(newParent), newParent, MegaRequestListener.getCPtr(listener), listener);
  }

  public void moveNode(MegaNode node, MegaNode newParent) {
    megaJNI.MegaApi_moveNode__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node, MegaNode.getCPtr(newParent), newParent);
  }

  public void copyNode(MegaNode node, MegaNode newParent, MegaRequestListener listener) {
    megaJNI.MegaApi_copyNode__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, MegaNode.getCPtr(newParent), newParent, MegaRequestListener.getCPtr(listener), listener);
  }

  public void copyNode(MegaNode node, MegaNode newParent) {
    megaJNI.MegaApi_copyNode__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node, MegaNode.getCPtr(newParent), newParent);
  }

  public void copyNode(MegaNode node, MegaNode newParent, String newName, MegaRequestListener listener) {
    megaJNI.MegaApi_copyNode__SWIG_2(swigCPtr, this, MegaNode.getCPtr(node), node, MegaNode.getCPtr(newParent), newParent, newName, MegaRequestListener.getCPtr(listener), listener);
  }

  public void copyNode(MegaNode node, MegaNode newParent, String newName) {
    megaJNI.MegaApi_copyNode__SWIG_3(swigCPtr, this, MegaNode.getCPtr(node), node, MegaNode.getCPtr(newParent), newParent, newName);
  }

  public void renameNode(MegaNode node, String newName, MegaRequestListener listener) {
    megaJNI.MegaApi_renameNode__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, newName, MegaRequestListener.getCPtr(listener), listener);
  }

  public void renameNode(MegaNode node, String newName) {
    megaJNI.MegaApi_renameNode__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node, newName);
  }

  public void remove(MegaNode node, MegaRequestListener listener) {
    megaJNI.MegaApi_remove__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, MegaRequestListener.getCPtr(listener), listener);
  }

  public void remove(MegaNode node) {
    megaJNI.MegaApi_remove__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public void cleanRubbishBin(MegaRequestListener listener) {
    megaJNI.MegaApi_cleanRubbishBin__SWIG_0(swigCPtr, this, MegaRequestListener.getCPtr(listener), listener);
  }

  public void cleanRubbishBin() {
    megaJNI.MegaApi_cleanRubbishBin__SWIG_1(swigCPtr, this);
  }

  public void sendFileToUser(MegaNode node, MegaUser user, MegaRequestListener listener) {
    megaJNI.MegaApi_sendFileToUser__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, MegaUser.getCPtr(user), user, MegaRequestListener.getCPtr(listener), listener);
  }

  public void sendFileToUser(MegaNode node, MegaUser user) {
    megaJNI.MegaApi_sendFileToUser__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node, MegaUser.getCPtr(user), user);
  }

  public void sendFileToUser(MegaNode node, String email, MegaRequestListener listener) {
    megaJNI.MegaApi_sendFileToUser__SWIG_2(swigCPtr, this, MegaNode.getCPtr(node), node, email, MegaRequestListener.getCPtr(listener), listener);
  }

  public void sendFileToUser(MegaNode node, String email) {
    megaJNI.MegaApi_sendFileToUser__SWIG_3(swigCPtr, this, MegaNode.getCPtr(node), node, email);
  }

  public void share(MegaNode node, MegaUser user, int level, MegaRequestListener listener) {
    megaJNI.MegaApi_share__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, MegaUser.getCPtr(user), user, level, MegaRequestListener.getCPtr(listener), listener);
  }

  public void share(MegaNode node, MegaUser user, int level) {
    megaJNI.MegaApi_share__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node, MegaUser.getCPtr(user), user, level);
  }

  public void share(MegaNode node, String email, int level, MegaRequestListener listener) {
    megaJNI.MegaApi_share__SWIG_2(swigCPtr, this, MegaNode.getCPtr(node), node, email, level, MegaRequestListener.getCPtr(listener), listener);
  }

  public void share(MegaNode node, String email, int level) {
    megaJNI.MegaApi_share__SWIG_3(swigCPtr, this, MegaNode.getCPtr(node), node, email, level);
  }

  public void importFileLink(String megaFileLink, MegaNode parent, MegaRequestListener listener) {
    megaJNI.MegaApi_importFileLink__SWIG_0(swigCPtr, this, megaFileLink, MegaNode.getCPtr(parent), parent, MegaRequestListener.getCPtr(listener), listener);
  }

  public void importFileLink(String megaFileLink, MegaNode parent) {
    megaJNI.MegaApi_importFileLink__SWIG_1(swigCPtr, this, megaFileLink, MegaNode.getCPtr(parent), parent);
  }

  public void getPublicNode(String megaFileLink, MegaRequestListener listener) {
    megaJNI.MegaApi_getPublicNode__SWIG_0(swigCPtr, this, megaFileLink, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getPublicNode(String megaFileLink) {
    megaJNI.MegaApi_getPublicNode__SWIG_1(swigCPtr, this, megaFileLink);
  }

  public void getThumbnail(MegaNode node, String dstFilePath, MegaRequestListener listener) {
    megaJNI.MegaApi_getThumbnail__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, dstFilePath, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getThumbnail(MegaNode node, String dstFilePath) {
    megaJNI.MegaApi_getThumbnail__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node, dstFilePath);
  }

  public void getPreview(MegaNode node, String dstFilePath, MegaRequestListener listener) {
    megaJNI.MegaApi_getPreview__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, dstFilePath, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getPreview(MegaNode node, String dstFilePath) {
    megaJNI.MegaApi_getPreview__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node, dstFilePath);
  }

  public void getUserAvatar(MegaUser user, String dstFilePath, MegaRequestListener listener) {
    megaJNI.MegaApi_getUserAvatar__SWIG_0(swigCPtr, this, MegaUser.getCPtr(user), user, dstFilePath, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getUserAvatar(MegaUser user, String dstFilePath) {
    megaJNI.MegaApi_getUserAvatar__SWIG_1(swigCPtr, this, MegaUser.getCPtr(user), user, dstFilePath);
  }

  public void getUserAvatar(String email_or_handle, String dstFilePath, MegaRequestListener listener) {
    megaJNI.MegaApi_getUserAvatar__SWIG_2(swigCPtr, this, email_or_handle, dstFilePath, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getUserAvatar(String email_or_handle, String dstFilePath) {
    megaJNI.MegaApi_getUserAvatar__SWIG_3(swigCPtr, this, email_or_handle, dstFilePath);
  }

  public void getUserAvatar(String dstFilePath, MegaRequestListener listener) {
    megaJNI.MegaApi_getUserAvatar__SWIG_4(swigCPtr, this, dstFilePath, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getUserAvatar(String dstFilePath) {
    megaJNI.MegaApi_getUserAvatar__SWIG_5(swigCPtr, this, dstFilePath);
  }

  public void getUserAttribute(MegaUser user, int type, MegaRequestListener listener) {
    megaJNI.MegaApi_getUserAttribute__SWIG_0(swigCPtr, this, MegaUser.getCPtr(user), user, type, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getUserAttribute(MegaUser user, int type) {
    megaJNI.MegaApi_getUserAttribute__SWIG_1(swigCPtr, this, MegaUser.getCPtr(user), user, type);
  }

  public void getUserAttribute(String email_or_handle, int type, MegaRequestListener listener) {
    megaJNI.MegaApi_getUserAttribute__SWIG_2(swigCPtr, this, email_or_handle, type, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getUserAttribute(String email_or_handle, int type) {
    megaJNI.MegaApi_getUserAttribute__SWIG_3(swigCPtr, this, email_or_handle, type);
  }

  public void getUserAttribute(int type, MegaRequestListener listener) {
    megaJNI.MegaApi_getUserAttribute__SWIG_4(swigCPtr, this, type, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getUserAttribute(int type) {
    megaJNI.MegaApi_getUserAttribute__SWIG_5(swigCPtr, this, type);
  }

  public void cancelGetThumbnail(MegaNode node, MegaRequestListener listener) {
    megaJNI.MegaApi_cancelGetThumbnail__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, MegaRequestListener.getCPtr(listener), listener);
  }

  public void cancelGetThumbnail(MegaNode node) {
    megaJNI.MegaApi_cancelGetThumbnail__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public void cancelGetPreview(MegaNode node, MegaRequestListener listener) {
    megaJNI.MegaApi_cancelGetPreview__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, MegaRequestListener.getCPtr(listener), listener);
  }

  public void cancelGetPreview(MegaNode node) {
    megaJNI.MegaApi_cancelGetPreview__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public void setThumbnail(MegaNode node, String srcFilePath, MegaRequestListener listener) {
    megaJNI.MegaApi_setThumbnail__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, srcFilePath, MegaRequestListener.getCPtr(listener), listener);
  }

  public void setThumbnail(MegaNode node, String srcFilePath) {
    megaJNI.MegaApi_setThumbnail__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node, srcFilePath);
  }

  public void setPreview(MegaNode node, String srcFilePath, MegaRequestListener listener) {
    megaJNI.MegaApi_setPreview__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, srcFilePath, MegaRequestListener.getCPtr(listener), listener);
  }

  public void setPreview(MegaNode node, String srcFilePath) {
    megaJNI.MegaApi_setPreview__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node, srcFilePath);
  }

  public void setAvatar(String srcFilePath, MegaRequestListener listener) {
    megaJNI.MegaApi_setAvatar__SWIG_0(swigCPtr, this, srcFilePath, MegaRequestListener.getCPtr(listener), listener);
  }

  public void setAvatar(String srcFilePath) {
    megaJNI.MegaApi_setAvatar__SWIG_1(swigCPtr, this, srcFilePath);
  }

  public void setUserAttribute(int type, String value, MegaRequestListener listener) {
    megaJNI.MegaApi_setUserAttribute__SWIG_0(swigCPtr, this, type, value, MegaRequestListener.getCPtr(listener), listener);
  }

  public void setUserAttribute(int type, String value) {
    megaJNI.MegaApi_setUserAttribute__SWIG_1(swigCPtr, this, type, value);
  }

  public void setCustomNodeAttribute(MegaNode node, String attrName, String value, MegaRequestListener listener) {
    megaJNI.MegaApi_setCustomNodeAttribute__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, attrName, value, MegaRequestListener.getCPtr(listener), listener);
  }

  public void setCustomNodeAttribute(MegaNode node, String attrName, String value) {
    megaJNI.MegaApi_setCustomNodeAttribute__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node, attrName, value);
  }

  public void exportNode(MegaNode node, MegaRequestListener listener) {
    megaJNI.MegaApi_exportNode__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, MegaRequestListener.getCPtr(listener), listener);
  }

  public void exportNode(MegaNode node) {
    megaJNI.MegaApi_exportNode__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public void exportNode(MegaNode node, long expireTime, MegaRequestListener listener) {
    megaJNI.MegaApi_exportNode__SWIG_2(swigCPtr, this, MegaNode.getCPtr(node), node, expireTime, MegaRequestListener.getCPtr(listener), listener);
  }

  public void exportNode(MegaNode node, long expireTime) {
    megaJNI.MegaApi_exportNode__SWIG_3(swigCPtr, this, MegaNode.getCPtr(node), node, expireTime);
  }

  public void disableExport(MegaNode node, MegaRequestListener listener) {
    megaJNI.MegaApi_disableExport__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, MegaRequestListener.getCPtr(listener), listener);
  }

  public void disableExport(MegaNode node) {
    megaJNI.MegaApi_disableExport__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public void fetchNodes(MegaRequestListener listener) {
    megaJNI.MegaApi_fetchNodes__SWIG_0(swigCPtr, this, MegaRequestListener.getCPtr(listener), listener);
  }

  public void fetchNodes() {
    megaJNI.MegaApi_fetchNodes__SWIG_1(swigCPtr, this);
  }

  public void getAccountDetails(MegaRequestListener listener) {
    megaJNI.MegaApi_getAccountDetails__SWIG_0(swigCPtr, this, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getAccountDetails() {
    megaJNI.MegaApi_getAccountDetails__SWIG_1(swigCPtr, this);
  }

  public void getExtendedAccountDetails(boolean sessions, boolean purchases, boolean transactions, MegaRequestListener listener) {
    megaJNI.MegaApi_getExtendedAccountDetails__SWIG_0(swigCPtr, this, sessions, purchases, transactions, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getExtendedAccountDetails(boolean sessions, boolean purchases, boolean transactions) {
    megaJNI.MegaApi_getExtendedAccountDetails__SWIG_1(swigCPtr, this, sessions, purchases, transactions);
  }

  public void getExtendedAccountDetails(boolean sessions, boolean purchases) {
    megaJNI.MegaApi_getExtendedAccountDetails__SWIG_2(swigCPtr, this, sessions, purchases);
  }

  public void getExtendedAccountDetails(boolean sessions) {
    megaJNI.MegaApi_getExtendedAccountDetails__SWIG_3(swigCPtr, this, sessions);
  }

  public void getExtendedAccountDetails() {
    megaJNI.MegaApi_getExtendedAccountDetails__SWIG_4(swigCPtr, this);
  }

  public void getPricing(MegaRequestListener listener) {
    megaJNI.MegaApi_getPricing__SWIG_0(swigCPtr, this, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getPricing() {
    megaJNI.MegaApi_getPricing__SWIG_1(swigCPtr, this);
  }

  public void getPaymentId(long productHandle, MegaRequestListener listener) {
    megaJNI.MegaApi_getPaymentId__SWIG_0(swigCPtr, this, productHandle, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getPaymentId(long productHandle) {
    megaJNI.MegaApi_getPaymentId__SWIG_1(swigCPtr, this, productHandle);
  }

  public void upgradeAccount(long productHandle, int paymentMethod, MegaRequestListener listener) {
    megaJNI.MegaApi_upgradeAccount__SWIG_0(swigCPtr, this, productHandle, paymentMethod, MegaRequestListener.getCPtr(listener), listener);
  }

  public void upgradeAccount(long productHandle, int paymentMethod) {
    megaJNI.MegaApi_upgradeAccount__SWIG_1(swigCPtr, this, productHandle, paymentMethod);
  }

  public void submitPurchaseReceipt(String receipt, MegaRequestListener listener) {
    megaJNI.MegaApi_submitPurchaseReceipt__SWIG_0(swigCPtr, this, receipt, MegaRequestListener.getCPtr(listener), listener);
  }

  public void submitPurchaseReceipt(String receipt) {
    megaJNI.MegaApi_submitPurchaseReceipt__SWIG_1(swigCPtr, this, receipt);
  }

  public void submitPurchaseReceipt(int gateway, String receipt, MegaRequestListener listener) {
    megaJNI.MegaApi_submitPurchaseReceipt__SWIG_2(swigCPtr, this, gateway, receipt, MegaRequestListener.getCPtr(listener), listener);
  }

  public void submitPurchaseReceipt(int gateway, String receipt) {
    megaJNI.MegaApi_submitPurchaseReceipt__SWIG_3(swigCPtr, this, gateway, receipt);
  }

  public void creditCardStore(String address1, String address2, String city, String province, String country, String postalcode, String firstname, String lastname, String creditcard, String expire_month, String expire_year, String cv2, MegaRequestListener listener) {
    megaJNI.MegaApi_creditCardStore__SWIG_0(swigCPtr, this, address1, address2, city, province, country, postalcode, firstname, lastname, creditcard, expire_month, expire_year, cv2, MegaRequestListener.getCPtr(listener), listener);
  }

  public void creditCardStore(String address1, String address2, String city, String province, String country, String postalcode, String firstname, String lastname, String creditcard, String expire_month, String expire_year, String cv2) {
    megaJNI.MegaApi_creditCardStore__SWIG_1(swigCPtr, this, address1, address2, city, province, country, postalcode, firstname, lastname, creditcard, expire_month, expire_year, cv2);
  }

  public void creditCardQuerySubscriptions(MegaRequestListener listener) {
    megaJNI.MegaApi_creditCardQuerySubscriptions__SWIG_0(swigCPtr, this, MegaRequestListener.getCPtr(listener), listener);
  }

  public void creditCardQuerySubscriptions() {
    megaJNI.MegaApi_creditCardQuerySubscriptions__SWIG_1(swigCPtr, this);
  }

  public void creditCardCancelSubscriptions(String reason, MegaRequestListener listener) {
    megaJNI.MegaApi_creditCardCancelSubscriptions__SWIG_0(swigCPtr, this, reason, MegaRequestListener.getCPtr(listener), listener);
  }

  public void creditCardCancelSubscriptions(String reason) {
    megaJNI.MegaApi_creditCardCancelSubscriptions__SWIG_1(swigCPtr, this, reason);
  }

  public void getPaymentMethods(MegaRequestListener listener) {
    megaJNI.MegaApi_getPaymentMethods__SWIG_0(swigCPtr, this, MegaRequestListener.getCPtr(listener), listener);
  }

  public void getPaymentMethods() {
    megaJNI.MegaApi_getPaymentMethods__SWIG_1(swigCPtr, this);
  }

  public String exportMasterKey() {
    return megaJNI.MegaApi_exportMasterKey(swigCPtr, this);
  }

  public void changePassword(String oldPassword, String newPassword, MegaRequestListener listener) {
    megaJNI.MegaApi_changePassword__SWIG_0(swigCPtr, this, oldPassword, newPassword, MegaRequestListener.getCPtr(listener), listener);
  }

  public void changePassword(String oldPassword, String newPassword) {
    megaJNI.MegaApi_changePassword__SWIG_1(swigCPtr, this, oldPassword, newPassword);
  }

  public void addContact(String email, MegaRequestListener listener) {
    megaJNI.MegaApi_addContact__SWIG_0(swigCPtr, this, email, MegaRequestListener.getCPtr(listener), listener);
  }

  public void addContact(String email) {
    megaJNI.MegaApi_addContact__SWIG_1(swigCPtr, this, email);
  }

  public void inviteContact(String email, String message, int action, MegaRequestListener listener) {
    megaJNI.MegaApi_inviteContact__SWIG_0(swigCPtr, this, email, message, action, MegaRequestListener.getCPtr(listener), listener);
  }

  public void inviteContact(String email, String message, int action) {
    megaJNI.MegaApi_inviteContact__SWIG_1(swigCPtr, this, email, message, action);
  }

  public void replyContactRequest(MegaContactRequest request, int action, MegaRequestListener listener) {
    megaJNI.MegaApi_replyContactRequest__SWIG_0(swigCPtr, this, MegaContactRequest.getCPtr(request), request, action, MegaRequestListener.getCPtr(listener), listener);
  }

  public void replyContactRequest(MegaContactRequest request, int action) {
    megaJNI.MegaApi_replyContactRequest__SWIG_1(swigCPtr, this, MegaContactRequest.getCPtr(request), request, action);
  }

  public void removeContact(MegaUser user, MegaRequestListener listener) {
    megaJNI.MegaApi_removeContact__SWIG_0(swigCPtr, this, MegaUser.getCPtr(user), user, MegaRequestListener.getCPtr(listener), listener);
  }

  public void removeContact(MegaUser user) {
    megaJNI.MegaApi_removeContact__SWIG_1(swigCPtr, this, MegaUser.getCPtr(user), user);
  }

  public void logout(MegaRequestListener listener) {
    megaJNI.MegaApi_logout__SWIG_0(swigCPtr, this, MegaRequestListener.getCPtr(listener), listener);
  }

  public void logout() {
    megaJNI.MegaApi_logout__SWIG_1(swigCPtr, this);
  }

  public void localLogout(MegaRequestListener listener) {
    megaJNI.MegaApi_localLogout__SWIG_0(swigCPtr, this, MegaRequestListener.getCPtr(listener), listener);
  }

  public void localLogout() {
    megaJNI.MegaApi_localLogout__SWIG_1(swigCPtr, this);
  }

  public void submitFeedback(int rating, String comment, MegaRequestListener listener) {
    megaJNI.MegaApi_submitFeedback__SWIG_0(swigCPtr, this, rating, comment, MegaRequestListener.getCPtr(listener), listener);
  }

  public void submitFeedback(int rating, String comment) {
    megaJNI.MegaApi_submitFeedback__SWIG_1(swigCPtr, this, rating, comment);
  }

  public void sendEvent(int eventType, String message, MegaRequestListener listener) {
    megaJNI.MegaApi_sendEvent__SWIG_0(swigCPtr, this, eventType, message, MegaRequestListener.getCPtr(listener), listener);
  }

  public void sendEvent(int eventType, String message) {
    megaJNI.MegaApi_sendEvent__SWIG_1(swigCPtr, this, eventType, message);
  }

  public void reportDebugEvent(String text, MegaRequestListener listener) {
    megaJNI.MegaApi_reportDebugEvent__SWIG_0(swigCPtr, this, text, MegaRequestListener.getCPtr(listener), listener);
  }

  public void reportDebugEvent(String text) {
    megaJNI.MegaApi_reportDebugEvent__SWIG_1(swigCPtr, this, text);
  }

  public void useHttpsOnly(boolean httpsOnly) {
    megaJNI.MegaApi_useHttpsOnly(swigCPtr, this, httpsOnly);
  }

  public boolean usingHttpsOnly() {
    return megaJNI.MegaApi_usingHttpsOnly(swigCPtr, this);
  }

  public void startUpload(String localPath, MegaNode parent, MegaTransferListener listener) {
    megaJNI.MegaApi_startUpload__SWIG_0(swigCPtr, this, localPath, MegaNode.getCPtr(parent), parent, MegaTransferListener.getCPtr(listener), listener);
  }

  public void startUpload(String localPath, MegaNode parent) {
    megaJNI.MegaApi_startUpload__SWIG_1(swigCPtr, this, localPath, MegaNode.getCPtr(parent), parent);
  }

  public void startUpload(String localPath, MegaNode parent, long mtime, MegaTransferListener listener) {
    megaJNI.MegaApi_startUpload__SWIG_2(swigCPtr, this, localPath, MegaNode.getCPtr(parent), parent, mtime, MegaTransferListener.getCPtr(listener), listener);
  }

  public void startUpload(String localPath, MegaNode parent, long mtime) {
    megaJNI.MegaApi_startUpload__SWIG_3(swigCPtr, this, localPath, MegaNode.getCPtr(parent), parent, mtime);
  }

  public void startUpload(String localPath, MegaNode parent, String fileName, MegaTransferListener listener) {
    megaJNI.MegaApi_startUpload__SWIG_4(swigCPtr, this, localPath, MegaNode.getCPtr(parent), parent, fileName, MegaTransferListener.getCPtr(listener), listener);
  }

  public void startUpload(String localPath, MegaNode parent, String fileName) {
    megaJNI.MegaApi_startUpload__SWIG_5(swigCPtr, this, localPath, MegaNode.getCPtr(parent), parent, fileName);
  }

  public void startUpload(String localPath, MegaNode parent, String fileName, long mtime, MegaTransferListener listener) {
    megaJNI.MegaApi_startUpload__SWIG_6(swigCPtr, this, localPath, MegaNode.getCPtr(parent), parent, fileName, mtime, MegaTransferListener.getCPtr(listener), listener);
  }

  public void startUpload(String localPath, MegaNode parent, String fileName, long mtime) {
    megaJNI.MegaApi_startUpload__SWIG_7(swigCPtr, this, localPath, MegaNode.getCPtr(parent), parent, fileName, mtime);
  }

  public void startDownload(MegaNode node, String localPath, MegaTransferListener listener) {
    megaJNI.MegaApi_startDownload__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, localPath, MegaTransferListener.getCPtr(listener), listener);
  }

  public void startDownload(MegaNode node, String localPath) {
    megaJNI.MegaApi_startDownload__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node, localPath);
  }

  public void startStreaming(MegaNode node, long startPos, long size, MegaTransferListener listener) {
    megaJNI.MegaApi_startStreaming(swigCPtr, this, MegaNode.getCPtr(node), node, startPos, size, MegaTransferListener.getCPtr(listener), listener);
  }

  public void cancelTransfer(MegaTransfer transfer, MegaRequestListener listener) {
    megaJNI.MegaApi_cancelTransfer__SWIG_0(swigCPtr, this, MegaTransfer.getCPtr(transfer), transfer, MegaRequestListener.getCPtr(listener), listener);
  }

  public void cancelTransfer(MegaTransfer transfer) {
    megaJNI.MegaApi_cancelTransfer__SWIG_1(swigCPtr, this, MegaTransfer.getCPtr(transfer), transfer);
  }

  public void cancelTransferByTag(int transferTag, MegaRequestListener listener) {
    megaJNI.MegaApi_cancelTransferByTag__SWIG_0(swigCPtr, this, transferTag, MegaRequestListener.getCPtr(listener), listener);
  }

  public void cancelTransferByTag(int transferTag) {
    megaJNI.MegaApi_cancelTransferByTag__SWIG_1(swigCPtr, this, transferTag);
  }

  public void cancelTransfers(int type, MegaRequestListener listener) {
    megaJNI.MegaApi_cancelTransfers__SWIG_0(swigCPtr, this, type, MegaRequestListener.getCPtr(listener), listener);
  }

  public void cancelTransfers(int type) {
    megaJNI.MegaApi_cancelTransfers__SWIG_1(swigCPtr, this, type);
  }

  public void pauseTransfers(boolean pause, MegaRequestListener listener) {
    megaJNI.MegaApi_pauseTransfers__SWIG_0(swigCPtr, this, pause, MegaRequestListener.getCPtr(listener), listener);
  }

  public void pauseTransfers(boolean pause) {
    megaJNI.MegaApi_pauseTransfers__SWIG_1(swigCPtr, this, pause);
  }

  public void pauseTransfers(boolean pause, int direction, MegaRequestListener listener) {
    megaJNI.MegaApi_pauseTransfers__SWIG_2(swigCPtr, this, pause, direction, MegaRequestListener.getCPtr(listener), listener);
  }

  public void pauseTransfers(boolean pause, int direction) {
    megaJNI.MegaApi_pauseTransfers__SWIG_3(swigCPtr, this, pause, direction);
  }

  public boolean areTransfersPaused(int direction) {
    return megaJNI.MegaApi_areTransfersPaused(swigCPtr, this, direction);
  }

  public void setUploadLimit(int bpslimit) {
    megaJNI.MegaApi_setUploadLimit(swigCPtr, this, bpslimit);
  }

  public void setDownloadMethod(int method) {
    megaJNI.MegaApi_setDownloadMethod(swigCPtr, this, method);
  }

  public void setUploadMethod(int method) {
    megaJNI.MegaApi_setUploadMethod(swigCPtr, this, method);
  }

  public int getDownloadMethod() {
    return megaJNI.MegaApi_getDownloadMethod(swigCPtr, this);
  }

  public int getUploadMethod() {
    return megaJNI.MegaApi_getUploadMethod(swigCPtr, this);
  }

  public MegaTransferList getTransfers() {
    long cPtr = megaJNI.MegaApi_getTransfers__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaTransferList(cPtr, true);
  }

  public MegaTransfer getTransferByTag(int transferTag) {
    long cPtr = megaJNI.MegaApi_getTransferByTag(swigCPtr, this, transferTag);
    return (cPtr == 0) ? null : new MegaTransfer(cPtr, true);
  }

  public MegaTransferList getTransfers(int type) {
    long cPtr = megaJNI.MegaApi_getTransfers__SWIG_1(swigCPtr, this, type);
    return (cPtr == 0) ? null : new MegaTransferList(cPtr, true);
  }

  public MegaTransferList getChildTransfers(int transferTag) {
    long cPtr = megaJNI.MegaApi_getChildTransfers(swigCPtr, this, transferTag);
    return (cPtr == 0) ? null : new MegaTransferList(cPtr, true);
  }

  public void update() {
    megaJNI.MegaApi_update(swigCPtr, this);
  }

  public boolean isWaiting() {
    return megaJNI.MegaApi_isWaiting(swigCPtr, this);
  }

  public int getNumPendingUploads() {
    return megaJNI.MegaApi_getNumPendingUploads(swigCPtr, this);
  }

  public int getNumPendingDownloads() {
    return megaJNI.MegaApi_getNumPendingDownloads(swigCPtr, this);
  }

  public int getTotalUploads() {
    return megaJNI.MegaApi_getTotalUploads(swigCPtr, this);
  }

  public int getTotalDownloads() {
    return megaJNI.MegaApi_getTotalDownloads(swigCPtr, this);
  }

  public void resetTotalDownloads() {
    megaJNI.MegaApi_resetTotalDownloads(swigCPtr, this);
  }

  public void resetTotalUploads() {
    megaJNI.MegaApi_resetTotalUploads(swigCPtr, this);
  }

  public long getTotalDownloadedBytes() {
    return megaJNI.MegaApi_getTotalDownloadedBytes(swigCPtr, this);
  }

  public long getTotalUploadedBytes() {
    return megaJNI.MegaApi_getTotalUploadedBytes(swigCPtr, this);
  }

  public void updateStats() {
    megaJNI.MegaApi_updateStats(swigCPtr, this);
  }

  public int getNumChildren(MegaNode parent) {
    return megaJNI.MegaApi_getNumChildren(swigCPtr, this, MegaNode.getCPtr(parent), parent);
  }

  public int getNumChildFiles(MegaNode parent) {
    return megaJNI.MegaApi_getNumChildFiles(swigCPtr, this, MegaNode.getCPtr(parent), parent);
  }

  public int getNumChildFolders(MegaNode parent) {
    return megaJNI.MegaApi_getNumChildFolders(swigCPtr, this, MegaNode.getCPtr(parent), parent);
  }

  public MegaNodeList getChildren(MegaNode parent, int order) {
    long cPtr = megaJNI.MegaApi_getChildren__SWIG_0(swigCPtr, this, MegaNode.getCPtr(parent), parent, order);
    return (cPtr == 0) ? null : new MegaNodeList(cPtr, true);
  }

  public MegaNodeList getChildren(MegaNode parent) {
    long cPtr = megaJNI.MegaApi_getChildren__SWIG_1(swigCPtr, this, MegaNode.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new MegaNodeList(cPtr, true);
  }

  public int getIndex(MegaNode node, int order) {
    return megaJNI.MegaApi_getIndex__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, order);
  }

  public int getIndex(MegaNode node) {
    return megaJNI.MegaApi_getIndex__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public MegaNode getChildNode(MegaNode parent, String name) {
    long cPtr = megaJNI.MegaApi_getChildNode(swigCPtr, this, MegaNode.getCPtr(parent), parent, name);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public MegaNode getParentNode(MegaNode node) {
    long cPtr = megaJNI.MegaApi_getParentNode(swigCPtr, this, MegaNode.getCPtr(node), node);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public String getNodePath(MegaNode node) {
    return megaJNI.MegaApi_getNodePath(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public MegaNode getNodeByPath(String path, MegaNode n) {
    long cPtr = megaJNI.MegaApi_getNodeByPath__SWIG_0(swigCPtr, this, path, MegaNode.getCPtr(n), n);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public MegaNode getNodeByPath(String path) {
    long cPtr = megaJNI.MegaApi_getNodeByPath__SWIG_1(swigCPtr, this, path);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public MegaNode getNodeByHandle(long h) {
    long cPtr = megaJNI.MegaApi_getNodeByHandle(swigCPtr, this, h);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public MegaContactRequest getContactRequestByHandle(long handle) {
    long cPtr = megaJNI.MegaApi_getContactRequestByHandle(swigCPtr, this, handle);
    return (cPtr == 0) ? null : new MegaContactRequest(cPtr, true);
  }

  public MegaUserList getContacts() {
    long cPtr = megaJNI.MegaApi_getContacts(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaUserList(cPtr, true);
  }

  public MegaUser getContact(String email) {
    long cPtr = megaJNI.MegaApi_getContact(swigCPtr, this, email);
    return (cPtr == 0) ? null : new MegaUser(cPtr, true);
  }

  public MegaNodeList getInShares(MegaUser user) {
    long cPtr = megaJNI.MegaApi_getInShares__SWIG_0(swigCPtr, this, MegaUser.getCPtr(user), user);
    return (cPtr == 0) ? null : new MegaNodeList(cPtr, true);
  }

  public MegaNodeList getInShares() {
    long cPtr = megaJNI.MegaApi_getInShares__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNodeList(cPtr, true);
  }

  public MegaShareList getInSharesList() {
    long cPtr = megaJNI.MegaApi_getInSharesList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaShareList(cPtr, true);
  }

  public boolean isShared(MegaNode node) {
    return megaJNI.MegaApi_isShared(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public boolean isOutShare(MegaNode node) {
    return megaJNI.MegaApi_isOutShare(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public boolean isInShare(MegaNode node) {
    return megaJNI.MegaApi_isInShare(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public boolean isPendingShare(MegaNode node) {
    return megaJNI.MegaApi_isPendingShare(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public MegaShareList getOutShares() {
    long cPtr = megaJNI.MegaApi_getOutShares__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaShareList(cPtr, true);
  }

  public MegaShareList getOutShares(MegaNode node) {
    long cPtr = megaJNI.MegaApi_getOutShares__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node);
    return (cPtr == 0) ? null : new MegaShareList(cPtr, true);
  }

  public MegaShareList getPendingOutShares() {
    long cPtr = megaJNI.MegaApi_getPendingOutShares__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaShareList(cPtr, true);
  }

  public MegaShareList getPendingOutShares(MegaNode node) {
    long cPtr = megaJNI.MegaApi_getPendingOutShares__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node);
    return (cPtr == 0) ? null : new MegaShareList(cPtr, true);
  }

  public MegaNodeList getPublicLinks() {
    long cPtr = megaJNI.MegaApi_getPublicLinks(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNodeList(cPtr, true);
  }

  public MegaContactRequestList getIncomingContactRequests() {
    long cPtr = megaJNI.MegaApi_getIncomingContactRequests(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaContactRequestList(cPtr, true);
  }

  public MegaContactRequestList getOutgoingContactRequests() {
    long cPtr = megaJNI.MegaApi_getOutgoingContactRequests(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaContactRequestList(cPtr, true);
  }

  public int getAccess(MegaNode node) {
    return megaJNI.MegaApi_getAccess(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public long getSize(MegaNode node) {
    return megaJNI.MegaApi_getSize(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public String getFingerprint(String filePath) {
    return megaJNI.MegaApi_getFingerprint__SWIG_0(swigCPtr, this, filePath);
  }

  public String getFingerprint(MegaNode node) {
    return megaJNI.MegaApi_getFingerprint__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public String getFingerprint(MegaInputStream inputStream, long mtime) {
    return megaJNI.MegaApi_getFingerprint__SWIG_2(swigCPtr, this, MegaInputStream.getCPtr(inputStream), inputStream, mtime);
  }

  public MegaNode getNodeByFingerprint(String fingerprint) {
    long cPtr = megaJNI.MegaApi_getNodeByFingerprint__SWIG_0(swigCPtr, this, fingerprint);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public MegaNode getNodeByFingerprint(String fingerprint, MegaNode parent) {
    long cPtr = megaJNI.MegaApi_getNodeByFingerprint__SWIG_1(swigCPtr, this, fingerprint, MegaNode.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public MegaNodeList getNodesByFingerprint(String fingerprint) {
    long cPtr = megaJNI.MegaApi_getNodesByFingerprint(swigCPtr, this, fingerprint);
    return (cPtr == 0) ? null : new MegaNodeList(cPtr, true);
  }

  public MegaNode getExportableNodeByFingerprint(String fingerprint, String name) {
    long cPtr = megaJNI.MegaApi_getExportableNodeByFingerprint__SWIG_0(swigCPtr, this, fingerprint, name);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public MegaNode getExportableNodeByFingerprint(String fingerprint) {
    long cPtr = megaJNI.MegaApi_getExportableNodeByFingerprint__SWIG_1(swigCPtr, this, fingerprint);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public boolean hasFingerprint(String fingerprint) {
    return megaJNI.MegaApi_hasFingerprint(swigCPtr, this, fingerprint);
  }

  public String getCRC(String filePath) {
    return megaJNI.MegaApi_getCRC__SWIG_0(swigCPtr, this, filePath);
  }

  public String getCRCFromFingerprint(String fingerprint) {
    return megaJNI.MegaApi_getCRCFromFingerprint(swigCPtr, this, fingerprint);
  }

  public String getCRC(MegaNode node) {
    return megaJNI.MegaApi_getCRC__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node);
  }

  public MegaNode getNodeByCRC(String crc, MegaNode parent) {
    long cPtr = megaJNI.MegaApi_getNodeByCRC(swigCPtr, this, crc, MegaNode.getCPtr(parent), parent);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public MegaError checkAccess(MegaNode node, int level) {
    return new MegaError(megaJNI.MegaApi_checkAccess(swigCPtr, this, MegaNode.getCPtr(node), node, level), true);
  }

  public MegaError checkMove(MegaNode node, MegaNode target) {
    return new MegaError(megaJNI.MegaApi_checkMove(swigCPtr, this, MegaNode.getCPtr(node), node, MegaNode.getCPtr(target), target), true);
  }

  public boolean isFilesystemAvailable() {
    return megaJNI.MegaApi_isFilesystemAvailable(swigCPtr, this);
  }

  public MegaNode getRootNode() {
    long cPtr = megaJNI.MegaApi_getRootNode(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public MegaNode getInboxNode() {
    long cPtr = megaJNI.MegaApi_getInboxNode(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public MegaNode getRubbishNode() {
    long cPtr = megaJNI.MegaApi_getRubbishNode(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNode(cPtr, true);
  }

  public void setDefaultFilePermissions(int permissions) {
    megaJNI.MegaApi_setDefaultFilePermissions(swigCPtr, this, permissions);
  }

  public int getDefaultFilePermissions() {
    return megaJNI.MegaApi_getDefaultFilePermissions(swigCPtr, this);
  }

  public void setDefaultFolderPermissions(int permissions) {
    megaJNI.MegaApi_setDefaultFolderPermissions(swigCPtr, this, permissions);
  }

  public int getDefaultFolderPermissions() {
    return megaJNI.MegaApi_getDefaultFolderPermissions(swigCPtr, this);
  }

  public long getBandwidthOverquotaDelay() {
    return megaJNI.MegaApi_getBandwidthOverquotaDelay(swigCPtr, this);
  }

  public MegaNodeList search(MegaNode node, String searchString, boolean recursive) {
    long cPtr = megaJNI.MegaApi_search__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, searchString, recursive);
    return (cPtr == 0) ? null : new MegaNodeList(cPtr, true);
  }

  public MegaNodeList search(MegaNode node, String searchString) {
    long cPtr = megaJNI.MegaApi_search__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node, searchString);
    return (cPtr == 0) ? null : new MegaNodeList(cPtr, true);
  }

  public boolean processMegaTree(MegaNode node, MegaTreeProcessor processor, boolean recursive) {
    return megaJNI.MegaApi_processMegaTree__SWIG_0(swigCPtr, this, MegaNode.getCPtr(node), node, MegaTreeProcessor.getCPtr(processor), processor, recursive);
  }

  public boolean processMegaTree(MegaNode node, MegaTreeProcessor processor) {
    return megaJNI.MegaApi_processMegaTree__SWIG_1(swigCPtr, this, MegaNode.getCPtr(node), node, MegaTreeProcessor.getCPtr(processor), processor);
  }

  public MegaNode createPublicFileNode(long handle, String key, String name, long size, long mtime, long parentHandle, String auth) {
    long cPtr = megaJNI.MegaApi_createPublicFileNode(swigCPtr, this, handle, key, name, size, mtime, parentHandle, auth);
    return (cPtr == 0) ? null : new MegaNode(cPtr, false);
  }

  public MegaNode createPublicFolderNode(long handle, String name, long parentHandle, String auth) {
    long cPtr = megaJNI.MegaApi_createPublicFolderNode(swigCPtr, this, handle, name, parentHandle, auth);
    return (cPtr == 0) ? null : new MegaNode(cPtr, false);
  }

  public String getVersion() {
    return megaJNI.MegaApi_getVersion(swigCPtr, this);
  }

  public String getUserAgent() {
    return megaJNI.MegaApi_getUserAgent(swigCPtr, this);
  }

  public void changeApiUrl(String apiURL, boolean disablepkp) {
    megaJNI.MegaApi_changeApiUrl__SWIG_0(swigCPtr, this, apiURL, disablepkp);
  }

  public void changeApiUrl(String apiURL) {
    megaJNI.MegaApi_changeApiUrl__SWIG_1(swigCPtr, this, apiURL);
  }

  public void retrySSLerrors(boolean enable) {
    megaJNI.MegaApi_retrySSLerrors(swigCPtr, this, enable);
  }

  public void setPublicKeyPinning(boolean enable) {
    megaJNI.MegaApi_setPublicKeyPinning(swigCPtr, this, enable);
  }

  public String escapeFsIncompatible(String filename) {
    return megaJNI.MegaApi_escapeFsIncompatible(swigCPtr, this, filename);
  }

  public String unescapeFsIncompatible(String name) {
    return megaJNI.MegaApi_unescapeFsIncompatible(swigCPtr, this, name);
  }

  public boolean createThumbnail(String imagePath, String dstPath) {
    return megaJNI.MegaApi_createThumbnail(swigCPtr, this, imagePath, dstPath);
  }

  public boolean createPreview(String imagePath, String dstPath) {
    return megaJNI.MegaApi_createPreview(swigCPtr, this, imagePath, dstPath);
  }

  public static String base64ToBase32(String base64) {
    return megaJNI.MegaApi_base64ToBase32(base64);
  }

  public static String base32ToBase64(String base32) {
    return megaJNI.MegaApi_base32ToBase64(base32);
  }

  public void loadBalancing(String service, MegaRequestListener listener) {
    megaJNI.MegaApi_loadBalancing__SWIG_0(swigCPtr, this, service, MegaRequestListener.getCPtr(listener), listener);
  }

  public void loadBalancing(String service) {
    megaJNI.MegaApi_loadBalancing__SWIG_1(swigCPtr, this, service);
  }

  public static String strdup(String buffer) {
    return megaJNI.MegaApi_strdup(buffer);
  }

  public static void removeRecursively(String path) {
    megaJNI.MegaApi_removeRecursively(path);
  }

  public boolean isOnline() {
    return megaJNI.MegaApi_isOnline(swigCPtr, this);
  }

  public final static int STATE_NONE = 0;
  public final static int STATE_SYNCED = STATE_NONE + 1;
  public final static int STATE_PENDING = STATE_SYNCED + 1;
  public final static int STATE_SYNCING = STATE_PENDING + 1;
  public final static int STATE_IGNORED = STATE_SYNCING + 1;

  public final static int LOG_LEVEL_FATAL = 0;
  public final static int LOG_LEVEL_ERROR = LOG_LEVEL_FATAL + 1;
  public final static int LOG_LEVEL_WARNING = LOG_LEVEL_ERROR + 1;
  public final static int LOG_LEVEL_INFO = LOG_LEVEL_WARNING + 1;
  public final static int LOG_LEVEL_DEBUG = LOG_LEVEL_INFO + 1;
  public final static int LOG_LEVEL_MAX = LOG_LEVEL_DEBUG + 1;

  public final static int ATTR_TYPE_THUMBNAIL = 0;
  public final static int ATTR_TYPE_PREVIEW = 1;

  public final static int USER_ATTR_AVATAR = 0;
  public final static int USER_ATTR_FIRSTNAME = 1;
  public final static int USER_ATTR_LASTNAME = 2;
  public final static int USER_ATTR_AUTHRING = 3;
  public final static int USER_ATTR_LAST_INTERACTION = 4;

  public final static int PAYMENT_METHOD_BALANCE = 0;
  public final static int PAYMENT_METHOD_PAYPAL = 1;
  public final static int PAYMENT_METHOD_ITUNES = 2;
  public final static int PAYMENT_METHOD_GOOGLE_WALLET = 3;
  public final static int PAYMENT_METHOD_BITCOIN = 4;
  public final static int PAYMENT_METHOD_UNIONPAY = 5;
  public final static int PAYMENT_METHOD_FORTUMO = 6;
  public final static int PAYMENT_METHOD_CREDIT_CARD = 8;
  public final static int PAYMENT_METHOD_CENTILI = 9;

  public final static int TRANSFER_METHOD_NORMAL = 0;
  public final static int TRANSFER_METHOD_ALTERNATIVE_PORT = 1;
  public final static int TRANSFER_METHOD_AUTO = 2;
  public final static int TRANSFER_METHOD_AUTO_NORMAL = 3;
  public final static int TRANSFER_METHOD_AUTO_ALTERNATIVE = 4;

  public final static int ORDER_NONE = 0;
  public final static int ORDER_DEFAULT_ASC = ORDER_NONE + 1;
  public final static int ORDER_DEFAULT_DESC = ORDER_DEFAULT_ASC + 1;
  public final static int ORDER_SIZE_ASC = ORDER_DEFAULT_DESC + 1;
  public final static int ORDER_SIZE_DESC = ORDER_SIZE_ASC + 1;
  public final static int ORDER_CREATION_ASC = ORDER_SIZE_DESC + 1;
  public final static int ORDER_CREATION_DESC = ORDER_CREATION_ASC + 1;
  public final static int ORDER_MODIFICATION_ASC = ORDER_CREATION_DESC + 1;
  public final static int ORDER_MODIFICATION_DESC = ORDER_MODIFICATION_ASC + 1;
  public final static int ORDER_ALPHABETICAL_ASC = ORDER_MODIFICATION_DESC + 1;
  public final static int ORDER_ALPHABETICAL_DESC = ORDER_ALPHABETICAL_ASC + 1;

}
