/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaAccountSession {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MegaAccountSession(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaAccountSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaAccountSession(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public long getCreationTimestamp() {
    return megaJNI.MegaAccountSession_getCreationTimestamp(swigCPtr, this);
  }

  public long getMostRecentUsage() {
    return megaJNI.MegaAccountSession_getMostRecentUsage(swigCPtr, this);
  }

  public String getUserAgent() {
    return megaJNI.MegaAccountSession_getUserAgent(swigCPtr, this);
  }

  public String getIP() {
    return megaJNI.MegaAccountSession_getIP(swigCPtr, this);
  }

  public String getCountry() {
    return megaJNI.MegaAccountSession_getCountry(swigCPtr, this);
  }

  public boolean isCurrent() {
    return megaJNI.MegaAccountSession_isCurrent(swigCPtr, this);
  }

  public boolean isAlive() {
    return megaJNI.MegaAccountSession_isAlive(swigCPtr, this);
  }

  public long getHandle() {
    return megaJNI.MegaAccountSession_getHandle(swigCPtr, this);
  }

  public MegaAccountSession() {
    this(megaJNI.new_MegaAccountSession(), true);
  }

}
