/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaUser {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MegaUser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaUser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaUser(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaUser copy() {
    long cPtr = megaJNI.MegaUser_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaUser(cPtr, true);
  }

  public String getEmail() {
    return megaJNI.MegaUser_getEmail(swigCPtr, this);
  }

  public long getHandle() {
    return megaJNI.MegaUser_getHandle(swigCPtr, this);
  }

  public int getVisibility() {
    return megaJNI.MegaUser_getVisibility(swigCPtr, this);
  }

  public long getTimestamp() {
    return megaJNI.MegaUser_getTimestamp(swigCPtr, this);
  }

  public boolean hasChanged(int changeType) {
    return megaJNI.MegaUser_hasChanged(swigCPtr, this, changeType);
  }

  public int getChanges() {
    return megaJNI.MegaUser_getChanges(swigCPtr, this);
  }

  public MegaUser() {
    this(megaJNI.new_MegaUser(), true);
  }

  public final static int VISIBILITY_UNKNOWN = -1;
  public final static int VISIBILITY_HIDDEN = 0;
  public final static int VISIBILITY_VISIBLE = VISIBILITY_HIDDEN + 1;
  public final static int VISIBILITY_ME = VISIBILITY_VISIBLE + 1;

  public final static int CHANGE_TYPE_AUTH = 0x01;
  public final static int CHANGE_TYPE_LSTINT = 0x02;
  public final static int CHANGE_TYPE_AVATAR = 0x04;
  public final static int CHANGE_TYPE_FIRSTNAME = 0x08;
  public final static int CHANGE_TYPE_LASTNAME = 0x10;

}
