/**
 * @file include/mega/transfer/ws/ws_upload_file.h
 * @brief Full definition of `mega::ws::WsUploadFile`, the per-file state owned
 *        by `UploadEngine::Impl` and consumed by `WsPool` / `WsConn` /
 *        `ChunkFingerprintMacUpdate`.
 *
 *        Promoted out of `src/transfer/ws/wsupload.cpp` so that sibling
 *        WS-internal translation units (`wsupload_engine.h`'s inline
 *        `UploadEngine::Impl` bodies + ws_conn.cpp / ws_pool.cpp) can
 *        dereference WsUploadFile members without relying on the class being
 *        TU-local to wsupload.cpp.
 *
 *        SDK-internal architecture header under `include/mega/transfer/ws/`
 *        alongside `ws_encryption.h` and `ws_pool_mgr.h`. Sibling translation
 *        units in `src/transfer/ws/` include it as
 *        `#include "mega/transfer/ws/ws_upload_file.h"`.
 *
 *        Small accessors and the hot-path read/write paths kept inline here
 *        because `wsupload_engine.h`'s inline `Impl` bodies call them under
 *        `uploadMutex` and rely on the compiler being able to inline through
 *        the call. Larger bodies (`readData`, `getTransferStats`, the WsPool-
 *        coupled `setPool` / `unsetPool` / `getCurrentSessionUrl`) live in
 *        `src/transfer/ws/ws_upload_file.cpp`.
 *
 * (c) 2026 by MEGA Privacy Kft, Csomad, Hungary
 *
 * This file is part of the MEGA SDK - Client Access Engine.
 *
 * Applications using the MEGA API must present a valid application key
 * and comply with the rules set forth in the Terms of Service.
 *
 * @copyright Simplified (2-clause) BSD License.
 */

#ifndef MEGA_TRANSFER_WS_WS_UPLOAD_FILE_H
#define MEGA_TRANSFER_WS_WS_UPLOAD_FILE_H 1

#ifdef MEGA_USE_WSUPLOAD

// File-internal WS types (WsPool, SteadyTime, WSUPLOAD_TRACE, kMiB,
// FailReason). SDK-internal architecture header under include/mega/transfer/ws/.
#include "mega/transfer/ws/wsupload_internal.h"

#include "mega/file.h" // File (for frontFile())
#include "mega/testhooks.h" // DEBUG_TEST_HOOK_WS_CONFIRMED_MACS_QUEUED (S16 Gate-3 seam)
#include "mega/filesystem.h" // FileAccess, LocalPath, FSLogging
#include "mega/transfer.h" // Transfer, SpeedController, TRANSFERSTATE_PAUSED
#include "mega/types.h" // m_off_t, m_time_t, dstime, byte, chunkmac_map
#include "mega/wsupload.h" // UploadEngine::{FailureDisposition, WsTransferStats}

#include <algorithm> // std::max (markRangeAcked interval coalescing)
#include <array>
#include <atomic>
#include <cstdint>
#include <iterator> // std::next / std::prev (markRangeAcked interval coalescing)
#include <memory>
#include <mutex>
#include <string>
#include <utility> // std::pair (mAckedIntervals)
#include <vector>

namespace mega
{

// Forward decls — full definitions come transitively via the includes above.
class MegaClient;
class SymmCipher;

namespace ws
{

// ---------- WsUploadFile (uses SDK File/FileAccess) ----------
class WsUploadFile
{
    class ActiveIOGuard;

public:
    static constexpr dstime RETRYINTERVAL{60 * 10};

    WsUploadFile(MegaClient& client, Transfer& t, const std::uint32_t fileno):
        mClient(client),
        mTransfer(&t),
        mLocalPath(frontFile(t)->getLocalname()),
        mFileNo(fileno),
        mSessionUrlHint(t.ws_session_url)
    {
        File* const f = frontFile(t);
        assert(f); // Transfer::files.front() must exist for PUT uploads
        mSize = f->size;
        mMtime = f->mtime;
        // mTransferKey / mCtrIv: populated later via snapshotCryptoMaterial() on the
        // worker thread, after preflightStart has guaranteed they are non-zero.
        if (!mSessionUrlHint.empty())
        {
            // Resume after restart:
            // continue from the last known contiguous position and keep already confirmed bytes.
            mHeadPos = std::min<m_off_t>(t.pos, mSize);
            mBytesConfirmed = std::min<m_off_t>(t.progresscompleted, mHeadPos);
            mLastReportedBytesConfirmed = mBytesConfirmed;
            mLastProgressReportBytes = mBytesConfirmed;
            mLastProgressReportDs = SteadyTime::ds();
        }

        WSUPLOAD_TRACE << "WsUploadFile: " << mLocalPath << " fileno=" << mFileNo << " size=" << mSize
                  << " mtime=" << mMtime << " [this = " << this << "]";

        // Preserve transfer-level paused state on enqueue (eg, restored from cache).
        if (t.state == TRANSFERSTATE_PAUSED)
        {
            mPaused = true;
        }
    }

    ~WsUploadFile() = default;

    // Snapshot write-once crypto material. Called exactly once from WsPool::getWsUploadFile()
    // under uploadMutex, after preflightStart has guaranteed Transfer::transferkey and ctriv
    // are populated (either restored from cache or generated by prepareUploadForWs()). After
    // this returns, worker threads only read the snapshotted copies -- never Transfer&.
    void snapshotCryptoMaterial(const Transfer& t)
    {
        mTransferKey = t.transferkey;
        mCtrIv = t.ctriv;
    }

    const std::array<byte, SymmCipher::KEYLENGTH>& transferKey() const noexcept
    {
        return mTransferKey;
    }

    int64_t ctrIv() const noexcept
    {
        return mCtrIv;
    }

    Transfer& transfer() const noexcept
    {
        return *mTransfer;
    }

    bool inPool() const noexcept
    {
        return mPool != nullptr;
    }

    // queue/pool bookkeeping
    bool continuingUpload(const dstime now) const
    {
        if (mAborted || mUploadCompletionTime != 0)
            return false;

        if (mUploadFailedTime != 0)
        {
            const dstime retryUntil =
                mRetryUntil ? mRetryUntil : (mUploadFailedTime + RETRYINTERVAL);
            return now >= retryUntil;
        }

        return true;
    }

    bool sourceMatchesExpected(const m_time_t observedMtime,
                               const m_off_t observedSize) const noexcept
    {
        return observedMtime == mMtime && observedSize == mSize;
    }

    UploadEngine::FailureDisposition classifyOpenFailure(const FileAccess* fa) const noexcept
    {
        if (!fa)
            return UploadEngine::FailureDisposition::Retryable;

        // Mirror legacy slot behavior for local-source failures: once WS has selected
        // a file, a non-transient open/stat failure means the local source is no longer
        // a valid upload candidate and should not burn the generic retry budget.
        return fa->retry ? UploadEngine::FailureDisposition::Retryable :
                           UploadEngine::FailureDisposition::Permanent;
    }

    // Pool bindings — bodies live in ws_upload_file.cpp (not inlined to keep
    // this header lean; the bodies dereference WsPool members and call
    // increaseNumPoolFiles / decreaseNumPoolFiles / clearUploadingFileLocked).
    void setPool(WsPool& p);
    void unsetPool();
    bool hasPool() const noexcept
    {
        return mPool != nullptr;
    }

    void closeFA()
    {
        // S12 Cluster-E: NEVER block on mReadMutex from under the engine mutex — a
        // reader stuck in a filesystem syscall (dying FUSE-backed source) holds
        // mReadMutex with the engine lock released; blocking here pins the engine mutex
        // (every pool + locallogout) to the syscall's duration. On contention the close
        // is skipped: the stuck reader's generation check discards its work anyway, and
        // the FA is replaced on the next open (mShareDelete keeps delete/move semantics
        // tolerable meanwhile).
        std::unique_lock<std::mutex> io(mReadMutex, std::try_to_lock);
        if (io.owns_lock())
        {
            mFA = nullptr;
        }
    }

    // S12 Cluster-E: acquire mReadMutex WITHOUT ever blocking while engineMutex is held
    // (see closeFA). Yields the engine lock while contended. Returns false when the
    // upload's work generation changed — or the engine began stopping — while yielding;
    // the caller treats that as an interrupted read. On true, ioLock owns mReadMutex
    // and engineMutex is held.
    // S13 round-3 (Cluster I+J): the yield slice BACKS OFF 1 -> 64 ms. The previous
    // fixed 1 ms unlock/relock churn starved threads BLOCKED on engineMutex for the
    // full duration of a stuck sibling read on platforms with barging mutex handoff
    // (Windows SRW, macOS first-fit pthread): the running spinner re-won the lock
    // every slice, so locallogout's freeq(PUT)->remove()/stop() never acquired and
    // NEITHER bounded escape hatch could fire — logout sat pinned to the stuck read
    // (macos_9454/win_9642: logoutMs ~= the whole 15 s injected read; Linux masked
    // the churn via futex wake ordering). With the backoff, the engine mutex stays
    // free in >=64 ms stretches, so a blocked acquirer wins within a few slices.
    bool lockReadYieldingEngine(std::unique_lock<std::mutex>& ioLock,
                                std::mutex& engineMutex,
                                const std::uint64_t expectedGeneration)
    {
        int backoffMs = 1;
        while (!ioLock.try_lock())
        {
            engineMutex.unlock();
            std::this_thread::sleep_for(std::chrono::milliseconds(backoffMs));
            backoffMs = std::min(backoffMs * 2, 64);
            engineMutex.lock();
            if (mWorkGeneration != expectedGeneration)
            {
                return false;
            }
            if (mEngineStopping && mEngineStopping->load(std::memory_order_acquire))
            {
                // Engine teardown in progress: bail as an interrupted read so the
                // locallogout quiesce window sees this worker exit instead of it
                // spinning on a parked/abandoned file.
                return false;
            }
        }
        return true;
    }

    // I/O (open on first read) — engineMutex is the single engine mutex.
    // Body in ws_upload_file.cpp.
    bool readData(char* buf,
                  const m_off_t pos,
                  const int len,
                  std::mutex& engineMutex,
                  const std::uint64_t expectedGeneration,
                  bool* interruptedByStateChange = nullptr);

    // S12 Cluster-E fix: BOUNDED — an IO holder blocked in an unbounded FS syscall
    // (dying FUSE-backed source path, network filesystem) must never hang the caller
    // (win_9515: the client thread spun here inside locallogout/freeq(PUT) until the CI
    // watchdog killed the job). Returns true when quiesced, false on timeout.
    // S15 round-1 (Cluster I, macos_9562): the bound must be WALL-CLOCK, not an
    // iteration count. The former `++waitedMs per sleep_for(1ms)` loop assumed one
    // iteration == 1 ms; on an oversubscribed macOS agent each iteration cost >=7.5 ms,
    // silently stretching the nominal 2 s bound across the entire 15 s stuck read
    // (logoutMs 15806 vs the 12 s test bound) while Windows (1.52x) and Linux (1.11x)
    // still timed out. steady_clock deadline, mirroring the locallogout quiesce loop.
    bool waitForNoIO(const int maxWaitMs) const
    {
        const auto deadline =
            std::chrono::steady_clock::now() + std::chrono::milliseconds(maxWaitMs);
        while (mActiveIO.load(std::memory_order_acquire) != 0)
        {
            if (std::chrono::steady_clock::now() >= deadline)
            {
                return false;
            }
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        }
        return true;
    }

    // server-confirmed progression
    void onServerConfirmedBytes(const m_off_t bytes)
    {
        mBytesConfirmed += bytes;
        if (!mFirstAckTime)
            mFirstAckTime = SteadyTime::ds();
        mClientActiveFilesTick = true;
    }

    // Tier 2 A whole-chunk-boundary rewind (loss-recovery). Record byte range
    // [begin,end) as server-acked (coalesced into the contiguous-interval set), so a
    // reconnect can re-queue ONLY the chunks NOT yet acked instead of every in-flight
    // chunk (cuts the multi-conn out-of-order-ack re-send waste). Always whole-chunk
    // granularity: callers pass (chunk.pos, chunk.pos+chunk.len) so (pos,len) stays
    // invariant across requeue (the len-blind ack-match is then safe). Per-attempt:
    // cleared by resetAttemptState. Caller must hold the engine uploadMutex (same
    // discipline as mBytesConfirmed). O(n) over the small live-interval count.
    void markRangeAcked(const m_off_t begin, const m_off_t end)
    {
        if (end <= begin)
            return;
        // Insert sorted by start, then coalesce touching/overlapping neighbours. The
        // interval count is bounded by chunks-in-flight (conns * pipeline depth), so a
        // linear insert is cheap and avoids pulling in a heavier interval container.
        std::pair<m_off_t, m_off_t> ins{begin, end};
        auto pos = mAckedIntervals.begin();
        while (pos != mAckedIntervals.end() && pos->first < ins.first)
            ++pos;
        pos = mAckedIntervals.insert(pos, ins);
        // Merge backward (previous interval may now touch/overlap the inserted one).
        if (pos != mAckedIntervals.begin())
        {
            auto prev = std::prev(pos);
            if (prev->second >= pos->first)
            {
                prev->second = std::max(prev->second, pos->second);
                mAckedIntervals.erase(pos);
                pos = prev;
            }
        }
        // Merge forward across all subsequent intervals the merged one now subsumes.
        auto next = std::next(pos);
        while (next != mAckedIntervals.end() && next->first <= pos->second)
        {
            pos->second = std::max(pos->second, next->second);
            next = mAckedIntervals.erase(next);
        }
    }

    // True iff [begin,end) is FULLY covered by a single coalesced acked interval.
    // Used by WsPool::retryChunksOnTheWireLocked to skip re-queueing an already-acked
    // whole chunk. Caller must hold the engine uploadMutex.
    bool rangeFullyAcked(const m_off_t begin, const m_off_t end) const
    {
        if (end <= begin)
            return true; // empty/EOF chunk: nothing to re-send
        for (const auto& iv: mAckedIntervals)
        {
            if (iv.first <= begin && iv.second >= end)
                return true;
            if (iv.first > begin)
                break; // intervals are sorted by start; no later one can cover begin
        }
        return false;
    }

    // Silent-byte-shortfall recovery (SDK-6298 F-2). Enumerate the whole-chunk ranges in
    // [0, mHeadPos) that are NOT covered by mAckedIntervals (the un-acked gaps left by the
    // orphan-ack purge), split each at chunk boundaries via chunkSizeAtPosition, and append
    // them to `out` as resend WsChunks (fileno = mFileNo, retryCount = 0). Re-sending exactly
    // the un-acked ranges — never mHeadPos/eofSet/mBytesConfirmed — re-reads + re-encrypts and
    // so rebuilds MAC state on the fresh in-flight entry (apply is position-keyed); the server
    // answers AlreadyOnServer (already ingested) or ingests it, either way crediting the
    // missing bytes with no over-credit. Body in ws_upload_file.cpp (needs chunkSizeAtPosition).
    // Caller must hold uploadMutex. Returns the number of chunks appended.
    std::size_t collectUnackedGapChunks(std::vector<WsChunk>& out) const;

    // progress coalescing (server-confirmed): report if delta or time threshold hit
    bool progressReportDue(const dstime now)
    {
        constexpr m_off_t kStepBytes = 64 * 1024; // 64 KiB
        constexpr dstime kStepTime = 5; // 0.5s (ds)
        const bool bytesDue = (mBytesConfirmed - mLastProgressReportBytes) >= kStepBytes;
        const bool timeDue =
            SteadyTime::difference(now, mLastProgressReportDs) >= static_cast<int32_t>(kStepTime);
        if (bytesDue || timeDue)
        {
            mLastProgressReportBytes = mBytesConfirmed;
            mLastProgressReportDs = now ? now : SteadyTime::ds();
            return true;
        }
        return false;
    }

    // accessors
    m_off_t size() const noexcept
    {
        return mSize;
    }

    m_off_t headPos() const noexcept
    {
        return mHeadPos;
    }

    void advanceHead(const int by) noexcept
    {
        mHeadPos += by;
    }

    bool eofSet() const noexcept
    {
        return mEofSet;
    }

    bool hasPendingBytesOrEofToSend() const noexcept
    {
        return headPos() < size() || !eofSet();
    }

    // Tail-completion watchdog candidate check (fu8 S9). True when every byte of the file is
    // server-confirmed but neither the completion frame (uploadCompleted) nor a failure ever
    // arrived — the lost-completion wedge state. Caller must hold uploadMutex (same discipline
    // as the surrounding pool bookkeeping; the fields are worker-written under that lock).
    bool completionWedgeCandidateLocked() const noexcept
    {
        return mSize > 0 && mBytesConfirmed >= mSize && !mUploadCompletionTime &&
               !mUploadFailedTime;
    }

    // Silent-byte-shortfall watchdog candidate check (SDK-6298 F-2). True when the file is
    // uploading-active, every byte + EOF has been SENT (nothing left to send normally), yet the
    // server-confirmed byte COUNT froze below size and no completion/failure arrived — the
    // orphan-ack purge wedge (an ack for a chunk whose in-flight entry was already purged hits
    // the "acked chunk not in-flight" early-return, so its byte credit is lost). This state sits
    // in the gap between the ack-stall watchdog (needs in-flight work) and the tail-completion
    // watchdog (needs mBytesConfirmed >= mSize). isUploading() already excludes paused/quota-held/
    // aborted/failed; the extra terms add "no completion" and "nothing pending to send" so a file
    // that still has bytes to push (which the pool would send unaided) is never a candidate.
    // Caller must hold uploadMutex (same discipline as completionWedgeCandidateLocked). The
    // per-file in-flight/resend emptiness is checked separately by the caller (pool-side state).
    bool silentByteShortfallCandidateLocked() const noexcept
    {
        return mSize > 0 && isUploading() && !mUploadCompletionTime && mBytesConfirmed < mSize &&
               !hasPendingBytesOrEofToSend();
    }

    void markEOF() noexcept
    {
        mEofSet = true;
    }

    std::uint32_t fileno() const noexcept
    {
        WSUPLOAD_TRACE << "[WsUploadFile::fileno] return mFileNo=" << mFileNo << " [this = " << this
                  << "]";
        return mFileNo;
    }

    const std::string& sessionUrlHint() const noexcept
    {
        return mSessionUrlHint;
    }

    void clearSessionUrlHintAndRestart()
    {
        mSessionUrlHint.clear();
        resetAttemptState();
    }

    // Body in ws_upload_file.cpp (needs WsPool::mUrl complete).
    bool getCurrentSessionUrl(std::string& outUrl) const;

    bool paused() const noexcept
    {
        WSUPLOAD_TRACE << "[WsUploadFile::paused] return mPaused=" << mPaused
                       << " mQuotaHeld=" << mQuotaHeld << " [this = " << this << "]";
        // A predictive quota hold makes the file ineligible everywhere paused()
        // gates, with zero added lock time (it is one extra bool read inside a
        // predicate already evaluated under uploadMutex).
        return mPaused || mQuotaHeld;
    }

    void setPaused(const bool p) noexcept
    {
        WSUPLOAD_TRACE << "[WsUploadFile::setPaused] p=" << p << " [this = " << this << "]";
        mPaused = p;
        invalidateOutstandingWork();
        closeFA();
    }

    // Predictive WS upload-quota hold (SDK-6298), an engine-side bit independent
    // of the user/global pause bit so the two compose by construction. Holding
    // invalidates outstanding work and closes the FA (same proven semantics as
    // pause): the in-flight chunk is requeued, the connection kept, and the file
    // resumes without a fresh onStart once released.
    void setQuotaHeld(const bool q) noexcept
    {
        WSUPLOAD_TRACE << "[WsUploadFile::setQuotaHeld] q=" << q << " [this = " << this << "]";
        mQuotaHeld = q;
        if (q)
        {
            invalidateOutstandingWork();
            closeFA();
        }
    }

    bool aborted() const noexcept
    {
        WSUPLOAD_TRACE << "[WsUploadFile::aborted] return mAborted=" << mAborted << " [this = " << this
                  << "]";
        return mAborted;
    }

    void setUploadStart(const dstime t) noexcept
    {
        WSUPLOAD_TRACE << "[WsUploadFile::setUploadStart] t=" << t << " [this = " << this << "]";
        invalidateOutstandingWork();
        mUploadStartTime = t;
        mUploadFailedTime = 0;
        mRetryUntil = 0;
        mReadFailureDisposition = UploadEngine::FailureDisposition::Retryable;
        // Keep speed reporting scoped to the current upload attempt in case we are in a resume.
        mAttemptBaseConfirmed = mBytesConfirmed;
        mAckSpeedController = SpeedController();
    }

    void setRetryUntil(const dstime when)
    {
        mRetryUntil = when;
    }

    void markFailedForRetry(const dstime retryUntil)
    {
        resetAttemptState();
        mReadFailureDisposition = UploadEngine::FailureDisposition::Retryable;
        if (!mUploadFailedTime)
            mUploadFailedTime = SteadyTime::ds();
        mRetryUntil = retryUntil ? retryUntil : (mUploadFailedTime + RETRYINTERVAL);
        closeFA();
    }

    m_off_t bytesConfirmed() const noexcept
    {
        return mBytesConfirmed;
    }

    std::uint64_t workGeneration() const noexcept
    {
        return mWorkGeneration;
    }

    bool hasFailed() const noexcept
    {
        return mUploadFailedTime != 0;
    }

    // Local failure bookkeeping; callers handle Transfer/app and crypto notifications.
    void uploadFailed(const FailReason reason)
    {
        resetAttemptState();
        if (reason != FailReason::ReadFailed)
        {
            mReadFailureDisposition = UploadEngine::FailureDisposition::Retryable;
        }
        mUploadFailedTime = SteadyTime::ds();
        mRetryUntil = mUploadFailedTime + RETRYINTERVAL;
        unsetPool();
        closeFA();
        LOG_warn << "[WsUploadFile::uploadFailed] file failed, reason=" << static_cast<int>(reason)
                 << " [this = " << this << "]";
    }

    UploadEngine::FailureDisposition readFailureDisposition() const noexcept
    {
        return mReadFailureDisposition;
    }

    void uploadCompleted(const char* response, const int len)
    {
        invalidateOutstandingWork();
        mUploadCompletionTime = SteadyTime::ds();
        // Fix up the progress counter on completion so the final onProgress reflects the
        // truth even if opcode-2 AlreadyOnServer events left mBytesConfirmed below mSize.
        if (mBytesConfirmed < mSize)
        {
            mBytesConfirmed = mSize;
        }
        unsetPool();
        closeFA();
        const auto dsElapsed = SteadyTime::difference(mUploadCompletionTime, mUploadStartTime);
        const auto attemptConfirmed =
            std::max<m_off_t>(0, mBytesConfirmed - mAttemptBaseConfirmed);
        const auto kbps = dsElapsed ? (attemptConfirmed / dsElapsed * kDsPerSecond / 1024) : 0;
        WSUPLOAD_TRACE << "[WsUploadFile::uploadCompleted] upload completed (server payload len=" << len
                 << ") Progress: " << mBytesConfirmed << " of " << mSize
                 << " bytes (attempt bytes: " << attemptConfirmed << ") @ ~" << kbps
                 << " KB/s [this = " << this << "]";
        (void)response; // response payload currently unused
    }

    // debug throughput (server-ACK basis)
    void maybeReportThroughput(const dstime now)
    {
        if (mUploadCompletionTime || mUploadFailedTime)
            return;
        if (mBytesConfirmed == mLastReportedBytesConfirmed)
            return;

        mLastReportedBytesConfirmed = mBytesConfirmed;

        const auto dsElapsed = SteadyTime::difference(now, mUploadStartTime);
        const auto attemptConfirmed =
            std::max<m_off_t>(0, mBytesConfirmed - mAttemptBaseConfirmed);
        const auto kbps = dsElapsed ? (attemptConfirmed / dsElapsed * kDsPerSecond / 1024) : 0;
        WSUPLOAD_TRACE << "[WsUploadFile::maybeReportThroughput] " << mBytesConfirmed << " of " << mSize
                  << " bytes (attempt bytes: " << attemptConfirmed << ") @ ~" << kbps
                  << " KB/s [this = " << this << "]";
    }

    bool isUploading() const noexcept
    {
        WSUPLOAD_TRACE << "[WsUploadFile::isUploading] mUploadStartTime= " << mUploadStartTime
                       << " mPaused=" << mPaused << " mQuotaHeld=" << mQuotaHeld
                       << " mAborted=" << mAborted << " mUploadFailedTime=" << mUploadFailedTime
                       << " returning "
                       << (mUploadStartTime != 0 && !mPaused && !mQuotaHeld && !mAborted &&
                           mUploadFailedTime == 0)
                       << " [this = " << this << "]";
        return mUploadStartTime != 0 && !mPaused && !mQuotaHeld && !mAborted &&
               mUploadFailedTime == 0;
    }

    void onRequestSent() noexcept
    {
        ++mNumRequests;
    }

    void onRequestFailed() noexcept
    {
        ++mNumFailedRequests;
    }

#ifndef NDEBUG
    bool markFirstByteSentForTesting() noexcept
    {
        if (mFirstByteSentForStats)
        {
            return false;
        }

        mFirstByteSentForStats = true;
        return true;
    }
#endif

    // Body in ws_upload_file.cpp.
    bool getTransferStats(UploadEngine::WsTransferStats& stats) const;

public: // accessed by engine
    // Accumulate server-confirmed chunk MAC updates on the worker threads.
    //
    // These are later drained and applied to Transfer::chunkmacs on the MegaClient thread,
    // ensuring Transfer mutation and transfercache serialization remain single-threaded.
    void queueConfirmedChunkMacs(chunkmac_map&& macs)
    {
        if (macs.size())
        {
            mConfirmedChunkMacs.emplace_back(std::move(macs));
            // S16 Gate-3 seam: lets the deterministic mid-transfer statecache exercise
            // observe queued-not-yet-drained MACs (StatecacheMidTransferPendingMacsRoundTrip
            // forces a commit + locallogout exactly while this queue is non-empty).
            DEBUG_TEST_HOOK_WS_CONFIRMED_MACS_QUEUED(fileno(),
                                                     mConfirmedChunkMacs.size());
        }
    }

    void drainConfirmedChunkMacs(std::vector<chunkmac_map>& out)
    {
        if (mConfirmedChunkMacs.empty())
        {
            return;
        }

        if (out.empty())
        {
            out.swap(mConfirmedChunkMacs);
            return;
        }

        for (auto& m: mConfirmedChunkMacs)
        {
            out.emplace_back(std::move(m));
        }
        mConfirmedChunkMacs.clear();
    }

    void clearConfirmedChunkMacs()
    {
        mConfirmedChunkMacs.clear();
    }

    bool mClientActiveFilesTick{false};
    WsPool* mPool{nullptr};
    // Tail-completion watchdog persistence clock (fu8 S11 F8: PER-FILE, was per-pool).
    // Written/read ONLY under uploadMutex by WsPoolMgr::checkPools: stamped the first tick
    // the file is observed bytes-complete-but-completionless with a quiescent (or no) pool,
    // cleared whenever that state does not hold, and cleared on fire. Lives on the file so
    // the clock survives pool retirement/rebinding — a wedged file has nothing to send, so
    // it never migrates with a refresh and a per-pool clock never accumulates the window.
    dstime mCompletionWedgeSinceDs{0};
    // Silent-byte-shortfall watchdog persistence clock (SDK-6298 F-2). Written/read ONLY under
    // uploadMutex by WsPoolMgr::checkPools: stamped the first tick the file is observed in the
    // orphan-ack shortfall wedge (silentByteShortfallCandidateLocked() true AND no per-file
    // in-flight/resend AND pool not server-throttled), cleared whenever that state does not hold,
    // and cleared on fire. Sibling of mCompletionWedgeSinceDs and keyed on the SAME tail-
    // completion window (a wedged file cannot migrate, so a per-file clock is the right grain).
    dstime mByteShortfallWedgeSinceDs{0};
    // S12 Cluster-E: points at the owning engine Impl's mStopping (leaked-alive on the
    // quiesce-or-leak logout path). readData checks it before EVERY MegaClient
    // dereference so an abandoned reader can never touch a destroyed client (ASAN UAF).
    const std::atomic<bool>* mEngineStopping{nullptr};

private:
    void invalidateOutstandingWork() noexcept
    {
        if (++mWorkGeneration == 0)
        {
            mWorkGeneration = 1;
        }
    }

    static File* frontFile(Transfer& t)
    {
        return t.files.empty() ? nullptr : *t.files.begin();
    }

    class ActiveIOGuard
    {
    public:
        explicit ActiveIOGuard(WsUploadFile& f):
            mFile(f)
        {
            mFile.mActiveIO.fetch_add(1, std::memory_order_acq_rel);
        }

        ~ActiveIOGuard()
        {
            mFile.mActiveIO.fetch_sub(1, std::memory_order_acq_rel);
        }

    private:
        WsUploadFile& mFile;
    };

    void resetAttemptState()
    {
        invalidateOutstandingWork();
        // Per-attempt counters/state. When we fail and retry we restart the upload from scratch
        mHeadPos = 0;
        mBytesConfirmed = 0;
        mAttemptBaseConfirmed = 0;
        mLastReportedBytesConfirmed = 0;
        mNumRequests = 0;
        mNumFailedRequests = 0;
        mFirstAckTime = 0;
        mLastProgressReportBytes = 0;
        mLastProgressReportDs = 0;
        mAckSpeedController = SpeedController();
        mEofSet = false;
        mUploadStartTime = 0;
        mUploadCompletionTime = 0;
        mClientActiveFilesTick = false;
        mConfirmedChunkMacs.clear();
        // Tier 2 A: acked-interval set is per-attempt. A reset rewinds mHeadPos to 0, so
        // every range must be re-sent; clearing here keeps it consistent with that rewind
        // and with mConfirmedChunkMacs (which is also cleared on attempt reset).
        mAckedIntervals.clear();
#ifndef NDEBUG
        mFirstByteSentForStats = false;
#endif
    }

    void markFailed(const UploadEngine::FailureDisposition disposition =
                        UploadEngine::FailureDisposition::Retryable)
    {
        resetAttemptState();
        mReadFailureDisposition = disposition;
        mUploadFailedTime = SteadyTime::ds();
        mRetryUntil = mUploadFailedTime + RETRYINTERVAL;
    }

private:
    MegaClient& mClient;
    Transfer* mTransfer{
        nullptr}; // identity only, used by callbacks; never dereferenced on worker threads
    // Worker threads only ever need these snapshots, copied before reads start.
    LocalPath mLocalPath; // set in constructor
    std::array<byte, SymmCipher::KEYLENGTH> mTransferKey{}; // set in snapshotCryptoMaterial()
    int64_t mCtrIv{0};
    std::unique_ptr<FileAccess> mFA{}; // blocking-opened on first read
    // Atomic so readers that do not hold engineMutex (e.g. the workGeneration() accessor
    // at wsupload.cpp ~700) observe a well-defined value. Writers still serialise via
    // engineMutex; the atomic adds cheap defence for future callers that forget.
    std::atomic<std::uint64_t> mWorkGeneration{1};
    std::mutex mReadMutex; // needed for Android because of lseek64+read
    std::atomic<unsigned> mActiveIO{0};

    std::uint32_t mFileNo{0};

    // Saved session URL to allow best-effort resume after restart.
    std::string mSessionUrlHint;

    // progress/state
    m_off_t mSize{0};
    m_off_t mHeadPos{0};
    m_off_t mBytesConfirmed{0};
    m_off_t mAttemptBaseConfirmed{0};
    m_off_t mLastReportedBytesConfirmed{0};
    m_off_t mNumRequests{0};
    m_off_t mNumFailedRequests{0};
    dstime mFirstAckTime{0};
    m_off_t mLastProgressReportBytes{0};
    dstime mLastProgressReportDs{0};
    mutable SpeedController mAckSpeedController{};
    m_time_t mMtime{0};
    UploadEngine::FailureDisposition mReadFailureDisposition{
        UploadEngine::FailureDisposition::Retryable};

    m_off_t mBytesSinceLastStat = 0;
    m_off_t mStatIntervalBytes = STAT_INTERVAL_LARGE;

    static constexpr m_off_t STAT_INTERVAL_LARGE = 8 * kMiB; // 8 MiB
    static constexpr m_off_t STAT_INTERVAL_SMALL = 2 * kMiB; // 2 MiB

    bool mEofSet{false};
    bool mAborted{false};
    bool mPaused{false};
    bool mQuotaHeld{false};

    dstime mUploadStartTime{0};
    dstime mUploadCompletionTime{0};
    dstime mUploadFailedTime{0};
    dstime mRetryUntil{0};

    // Server-confirmed chunk MAC updates awaiting application on the client thread.
    std::vector<chunkmac_map> mConfirmedChunkMacs;
    // Tier 2 A (loss-recovery): coalesced contiguous set of server-acked byte ranges
    // for THIS attempt, advanced from opcode-1/7 acks at whole-chunk boundaries. Read by
    // WsPool::retryChunksOnTheWireLocked to skip re-queueing already-acked chunks on a
    // reconnect. Sorted by interval start, non-overlapping (coalesced in markRangeAcked).
    // Per-attempt: cleared in resetAttemptState alongside mConfirmedChunkMacs. Written /
    // read only under the engine uploadMutex.
    std::vector<std::pair<m_off_t, m_off_t>> mAckedIntervals;
#ifndef NDEBUG
    bool mFirstByteSentForStats{false};
#endif
};

} // namespace ws
} // namespace mega

#endif // MEGA_USE_WSUPLOAD

#endif // MEGA_TRANSFER_WS_WS_UPLOAD_FILE_H
