/**
 * @file include/mega/transfer/ws/ws_upload_file.h
 * @brief Full definition of `mega::ws::WsUploadFile`, the per-file state owned
 *        by `UploadEngine::Impl` and consumed by `WsPool` / `WsConn` /
 *        `ChunkFingerprintMacUpdate`.
 *
 *        Promoted out of `src/transfer/ws/wsupload.cpp` in fu7-16 Goal 2.Step2
 *        so that sibling WS-internal translation units (`wsupload_engine.h`'s
 *        inline `UploadEngine::Impl` bodies + the future ws_conn.cpp /
 *        ws_pool.cpp splits) can dereference WsUploadFile members without
 *        relying on the class being TU-local to wsupload.cpp. See
 *        `Goal2_cross_followup_refactor_sweep/domain_coupling_map.md` (§1
 *        WsUploadFile inventory + §6 Step 2 row) for the coupling rationale.
 *
 *        SDK-internal architecture header (fu7-17 Goal 1.a relocated it from
 *        `src/transfer/ws/` to `include/mega/transfer/ws/` alongside
 *        `ws_encryption.h` and `ws_pool_mgr.h`). Sibling translation units in
 *        `src/transfer/ws/` include it as
 *        `#include "mega/transfer/ws/ws_upload_file.h"`.
 *
 *        Small accessors and the hot-path read/write paths kept inline here
 *        because `wsupload_engine.h`'s inline `Impl` bodies call them under
 *        `uploadMutex` and rely on the compiler being able to inline through
 *        the call. Larger bodies (`readData`, `getTransferStats`, the WsPool-
 *        coupled `setPool` / `unsetPool` / `getCurrentSessionUrl`) live in
 *        `src/transfer/ws/ws_upload_file.cpp`.
 *
 * (c) 2026 by Mega Limited, Auckland, New Zealand
 *
 * This file is part of the MEGA SDK - Client Access Engine.
 *
 * Applications using the MEGA API must present a valid application key
 * and comply with the rules set forth in the Terms of Service.
 *
 * @copyright Simplified (2-clause) BSD License.
 */

#ifndef MEGA_TRANSFER_WS_WS_UPLOAD_FILE_H
#define MEGA_TRANSFER_WS_WS_UPLOAD_FILE_H 1

#ifdef MEGA_USE_WSUPLOAD

// File-internal WS types (WsPool, SteadyTime, WSUPLOAD_TRACE, kMiB,
// FailReason). SDK-internal architecture header under include/mega/transfer/ws/
// (fu7-17 Goal 1.a relocated it alongside ws_encryption.h / ws_pool_mgr.h).
#include "mega/transfer/ws/wsupload_internal.h"

#include "mega/file.h" // File (for frontFile())
#include "mega/filesystem.h" // FileAccess, LocalPath, FSLogging
#include "mega/transfer.h" // Transfer, SpeedController, TRANSFERSTATE_PAUSED
#include "mega/types.h" // m_off_t, m_time_t, dstime, byte, chunkmac_map
#include "mega/wsupload.h" // UploadEngine::{FailureDisposition, WsTransferStats}

#include <array>
#include <atomic>
#include <cstdint>
#include <memory>
#include <mutex>
#include <string>
#include <vector>

namespace mega
{

// Forward decls — full definitions come transitively via the includes above.
class MegaClient;
class SymmCipher;

namespace ws
{

// ---------- WsUploadFile (uses SDK File/FileAccess) ----------
class WsUploadFile
{
    class ActiveIOGuard;

public:
    static constexpr dstime RETRYINTERVAL{60 * 10};

    WsUploadFile(MegaClient& client, Transfer& t, const std::uint32_t fileno):
        mClient(client),
        mTransfer(&t),
        mLocalPath(frontFile(t)->getLocalname()),
        mFileNo(fileno),
        mSessionUrlHint(t.ws_session_url)
    {
        File* const f = frontFile(t);
        assert(f); // Transfer::files.front() must exist for PUT uploads
        mSize = f->size;
        mMtime = f->mtime;
        // mTransferKey / mCtrIv: populated later via snapshotCryptoMaterial() on the
        // worker thread, after preflightStart has guaranteed they are non-zero.
        if (!mSessionUrlHint.empty())
        {
            // Resume after restart:
            // continue from the last known contiguous position and keep already confirmed bytes.
            mHeadPos = std::min<m_off_t>(t.pos, mSize);
            mBytesConfirmed = std::min<m_off_t>(t.progresscompleted, mHeadPos);
            mLastReportedBytesConfirmed = mBytesConfirmed;
            mLastProgressReportBytes = mBytesConfirmed;
            mLastProgressReportDs = SteadyTime::ds();
        }

        WSUPLOAD_TRACE << "WsUploadFile: " << mLocalPath << " fileno=" << mFileNo << " size=" << mSize
                  << " mtime=" << mMtime << " [this = " << this << "]";

        // Preserve transfer-level paused state on enqueue (eg, restored from cache).
        if (t.state == TRANSFERSTATE_PAUSED)
        {
            mPaused = true;
        }
    }

    ~WsUploadFile() = default;

    // Snapshot write-once crypto material. Called exactly once from WsPool::getWsUploadFile()
    // under uploadMutex, after preflightStart has guaranteed Transfer::transferkey and ctriv
    // are populated (either restored from cache or generated by prepareUploadForWs()). After
    // this returns, worker threads only read the snapshotted copies -- never Transfer&.
    void snapshotCryptoMaterial(const Transfer& t)
    {
        mTransferKey = t.transferkey;
        mCtrIv = t.ctriv;
    }

    const std::array<byte, SymmCipher::KEYLENGTH>& transferKey() const noexcept
    {
        return mTransferKey;
    }

    int64_t ctrIv() const noexcept
    {
        return mCtrIv;
    }

    Transfer& transfer() const noexcept
    {
        return *mTransfer;
    }

    bool inPool() const noexcept
    {
        return mPool != nullptr;
    }

    // queue/pool bookkeeping
    bool continuingUpload(const dstime now) const
    {
        if (mAborted || mUploadCompletionTime != 0)
            return false;

        if (mUploadFailedTime != 0)
        {
            const dstime retryUntil =
                mRetryUntil ? mRetryUntil : (mUploadFailedTime + RETRYINTERVAL);
            return now >= retryUntil;
        }

        return true;
    }

    bool sourceMatchesExpected(const m_time_t observedMtime,
                               const m_off_t observedSize) const noexcept
    {
        return observedMtime == mMtime && observedSize == mSize;
    }

    UploadEngine::FailureDisposition classifyOpenFailure(const FileAccess* fa) const noexcept
    {
        if (!fa)
            return UploadEngine::FailureDisposition::Retryable;

        // Mirror legacy slot behavior for local-source failures: once WS has selected
        // a file, a non-transient open/stat failure means the local source is no longer
        // a valid upload candidate and should not burn the generic retry budget.
        return fa->retry ? UploadEngine::FailureDisposition::Retryable :
                           UploadEngine::FailureDisposition::Permanent;
    }

    // Pool bindings — bodies live in ws_upload_file.cpp (not inlined to keep
    // this header lean; the bodies dereference WsPool members and call
    // increaseNumPoolFiles / decreaseNumPoolFiles / clearUploadingFileLocked).
    void setPool(WsPool& p);
    void unsetPool();
    bool hasPool() const noexcept
    {
        return mPool != nullptr;
    }

    void closeFA()
    {
        std::lock_guard<std::mutex> io(mReadMutex);
        mFA = nullptr;
    }

    // I/O (open on first read) — engineMutex is the single engine mutex.
    // Body in ws_upload_file.cpp.
    bool readData(char* buf,
                  const m_off_t pos,
                  const int len,
                  std::mutex& engineMutex,
                  const std::uint64_t expectedGeneration,
                  bool* interruptedByStateChange = nullptr);

    void waitForNoIO() const
    {
        while (mActiveIO.load(std::memory_order_acquire) != 0)
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
    }

    // server-confirmed progression
    void onServerConfirmedBytes(const m_off_t bytes)
    {
        mBytesConfirmed += bytes;
        if (!mFirstAckTime)
            mFirstAckTime = SteadyTime::ds();
        mClientActiveFilesTick = true;
    }

    // progress coalescing (server-confirmed): report if delta or time threshold hit
    bool progressReportDue(const dstime now)
    {
        constexpr m_off_t kStepBytes = 64 * 1024; // 64 KiB
        constexpr dstime kStepTime = 5; // 0.5s (ds)
        const bool bytesDue = (mBytesConfirmed - mLastProgressReportBytes) >= kStepBytes;
        const bool timeDue =
            SteadyTime::difference(now, mLastProgressReportDs) >= static_cast<int32_t>(kStepTime);
        if (bytesDue || timeDue)
        {
            mLastProgressReportBytes = mBytesConfirmed;
            mLastProgressReportDs = now ? now : SteadyTime::ds();
            return true;
        }
        return false;
    }

    // accessors
    m_off_t size() const noexcept
    {
        return mSize;
    }

    m_off_t headPos() const noexcept
    {
        return mHeadPos;
    }

    void advanceHead(const int by) noexcept
    {
        mHeadPos += by;
    }

    bool eofSet() const noexcept
    {
        return mEofSet;
    }

    bool hasPendingBytesOrEofToSend() const noexcept
    {
        return headPos() < size() || !eofSet();
    }

    void markEOF() noexcept
    {
        mEofSet = true;
    }

    std::uint32_t fileno() const noexcept
    {
        WSUPLOAD_TRACE << "[WsUploadFile::fileno] return mFileNo=" << mFileNo << " [this = " << this
                  << "]";
        return mFileNo;
    }

    const std::string& sessionUrlHint() const noexcept
    {
        return mSessionUrlHint;
    }

    void clearSessionUrlHintAndRestart()
    {
        mSessionUrlHint.clear();
        resetAttemptState();
    }

    // Body in ws_upload_file.cpp (needs WsPool::mUrl complete).
    bool getCurrentSessionUrl(std::string& outUrl) const;

    bool paused() const noexcept
    {
        WSUPLOAD_TRACE << "[WsUploadFile::paused] return mPaused=" << mPaused << " [this = " << this
                  << "]";
        return mPaused;
    }

    void setPaused(const bool p) noexcept
    {
        WSUPLOAD_TRACE << "[WsUploadFile::setPaused] p=" << p << " [this = " << this << "]";
        mPaused = p;
        invalidateOutstandingWork();
        closeFA();
    }

    bool aborted() const noexcept
    {
        WSUPLOAD_TRACE << "[WsUploadFile::aborted] return mAborted=" << mAborted << " [this = " << this
                  << "]";
        return mAborted;
    }

    void setUploadStart(const dstime t) noexcept
    {
        WSUPLOAD_TRACE << "[WsUploadFile::setUploadStart] t=" << t << " [this = " << this << "]";
        invalidateOutstandingWork();
        mUploadStartTime = t;
        mUploadFailedTime = 0;
        mRetryUntil = 0;
        mReadFailureDisposition = UploadEngine::FailureDisposition::Retryable;
        // Keep speed reporting scoped to the current upload attempt in case we are in a resume.
        mAttemptBaseConfirmed = mBytesConfirmed;
        mAckSpeedController = SpeedController();
    }

    void setRetryUntil(const dstime when)
    {
        mRetryUntil = when;
    }

    void markFailedForRetry(const dstime retryUntil)
    {
        resetAttemptState();
        mReadFailureDisposition = UploadEngine::FailureDisposition::Retryable;
        if (!mUploadFailedTime)
            mUploadFailedTime = SteadyTime::ds();
        mRetryUntil = retryUntil ? retryUntil : (mUploadFailedTime + RETRYINTERVAL);
        closeFA();
    }

    m_off_t bytesConfirmed() const noexcept
    {
        return mBytesConfirmed;
    }

    std::uint64_t workGeneration() const noexcept
    {
        return mWorkGeneration;
    }

    bool hasFailed() const noexcept
    {
        return mUploadFailedTime != 0;
    }

    // hooks (Phase 2/5 will notify Transfer/app + crypto)
    void uploadFailed(const FailReason reason)
    {
        resetAttemptState();
        if (reason != FailReason::ReadFailed)
        {
            mReadFailureDisposition = UploadEngine::FailureDisposition::Retryable;
        }
        mUploadFailedTime = SteadyTime::ds();
        mRetryUntil = mUploadFailedTime + RETRYINTERVAL;
        unsetPool();
        closeFA();
        LOG_warn << "[WsUploadFile::uploadFailed] file failed, reason=" << static_cast<int>(reason)
                 << " [this = " << this << "]";
    }

    UploadEngine::FailureDisposition readFailureDisposition() const noexcept
    {
        return mReadFailureDisposition;
    }

    void uploadCompleted(const char* response, const int len)
    {
        invalidateOutstandingWork();
        mUploadCompletionTime = SteadyTime::ds();
        // Fix up the progress counter on completion so the final onProgress reflects the
        // truth even if opcode-2 AlreadyOnServer events left mBytesConfirmed below mSize.
        if (mBytesConfirmed < mSize)
        {
            mBytesConfirmed = mSize;
        }
        unsetPool();
        closeFA();
        const auto dsElapsed = SteadyTime::difference(mUploadCompletionTime, mUploadStartTime);
        const auto attemptConfirmed =
            std::max<m_off_t>(0, mBytesConfirmed - mAttemptBaseConfirmed);
        const auto kbps = dsElapsed ? (attemptConfirmed / dsElapsed * kDsPerSecond / 1024) : 0;
        WSUPLOAD_TRACE << "[WsUploadFile::uploadCompleted] upload completed (server payload len=" << len
                 << ") Progress: " << mBytesConfirmed << " of " << mSize
                 << " bytes (attempt bytes: " << attemptConfirmed << ") @ ~" << kbps
                 << " KB/s [this = " << this << "]";
        (void)response; // Phase 5: use payload (e.g. MAC/fingerprint)
    }

    // debug throughput (server-ACK basis)
    void maybeReportThroughput(const dstime now)
    {
        if (mUploadCompletionTime || mUploadFailedTime)
            return;
        if (mBytesConfirmed == mLastReportedBytesConfirmed)
            return;

        mLastReportedBytesConfirmed = mBytesConfirmed;

        const auto dsElapsed = SteadyTime::difference(now, mUploadStartTime);
        const auto attemptConfirmed =
            std::max<m_off_t>(0, mBytesConfirmed - mAttemptBaseConfirmed);
        const auto kbps = dsElapsed ? (attemptConfirmed / dsElapsed * kDsPerSecond / 1024) : 0;
        WSUPLOAD_TRACE << "[WsUploadFile::maybeReportThroughput] " << mBytesConfirmed << " of " << mSize
                  << " bytes (attempt bytes: " << attemptConfirmed << ") @ ~" << kbps
                  << " KB/s [this = " << this << "]";
    }

    bool isUploading() const noexcept
    {
        WSUPLOAD_TRACE << "[WsUploadFile::isUploading] mUploadStartTime= " << mUploadStartTime
                  << " mPaused=" << mPaused << " mAborted=" << mAborted
                  << " mUploadFailedTime=" << mUploadFailedTime << " returning "
                  << (mUploadStartTime != 0 && !mPaused && !mAborted && mUploadFailedTime == 0)
                  << " [this = " << this << "]";
        return mUploadStartTime != 0 && !mPaused && !mAborted && mUploadFailedTime == 0;
    }

    void onRequestSent() noexcept
    {
        ++mNumRequests;
    }

    void onRequestFailed() noexcept
    {
        ++mNumFailedRequests;
    }

#ifndef NDEBUG
    bool markFirstByteSentForTesting() noexcept
    {
        if (mFirstByteSentForStats)
        {
            return false;
        }

        mFirstByteSentForStats = true;
        return true;
    }
#endif

    // Body in ws_upload_file.cpp.
    bool getTransferStats(UploadEngine::WsTransferStats& stats) const;

public: // accessed by engine
    // Accumulate server-confirmed chunk MAC updates on the worker threads.
    //
    // These are later drained and applied to Transfer::chunkmacs on the MegaClient thread,
    // ensuring Transfer mutation and transfercache serialization remain single-threaded.
    void queueConfirmedChunkMacs(chunkmac_map&& macs)
    {
        if (macs.size())
        {
            mConfirmedChunkMacs.emplace_back(std::move(macs));
        }
    }

    void drainConfirmedChunkMacs(std::vector<chunkmac_map>& out)
    {
        if (mConfirmedChunkMacs.empty())
        {
            return;
        }

        if (out.empty())
        {
            out.swap(mConfirmedChunkMacs);
            return;
        }

        for (auto& m: mConfirmedChunkMacs)
        {
            out.emplace_back(std::move(m));
        }
        mConfirmedChunkMacs.clear();
    }

    void clearConfirmedChunkMacs()
    {
        mConfirmedChunkMacs.clear();
    }

    bool mClientActiveFilesTick{false};
    WsPool* mPool{nullptr};

private:
    void invalidateOutstandingWork() noexcept
    {
        if (++mWorkGeneration == 0)
        {
            mWorkGeneration = 1;
        }
    }

    static File* frontFile(Transfer& t)
    {
        return t.files.empty() ? nullptr : *t.files.begin();
    }

    class ActiveIOGuard
    {
    public:
        explicit ActiveIOGuard(WsUploadFile& f):
            mFile(f)
        {
            mFile.mActiveIO.fetch_add(1, std::memory_order_acq_rel);
        }

        ~ActiveIOGuard()
        {
            mFile.mActiveIO.fetch_sub(1, std::memory_order_acq_rel);
        }

    private:
        WsUploadFile& mFile;
    };

    void resetAttemptState()
    {
        invalidateOutstandingWork();
        // Per-attempt counters/state. When we fail and retry we restart the upload from scratch
        mHeadPos = 0;
        mBytesConfirmed = 0;
        mAttemptBaseConfirmed = 0;
        mLastReportedBytesConfirmed = 0;
        mNumRequests = 0;
        mNumFailedRequests = 0;
        mFirstAckTime = 0;
        mLastProgressReportBytes = 0;
        mLastProgressReportDs = 0;
        mAckSpeedController = SpeedController();
        mEofSet = false;
        mUploadStartTime = 0;
        mUploadCompletionTime = 0;
        mClientActiveFilesTick = false;
        mConfirmedChunkMacs.clear();
#ifndef NDEBUG
        mFirstByteSentForStats = false;
#endif
    }

    void markFailed(const UploadEngine::FailureDisposition disposition =
                        UploadEngine::FailureDisposition::Retryable)
    {
        resetAttemptState();
        mReadFailureDisposition = disposition;
        mUploadFailedTime = SteadyTime::ds();
        mRetryUntil = mUploadFailedTime + RETRYINTERVAL;
    }

private:
    MegaClient& mClient;
    Transfer* mTransfer{
        nullptr}; // identity only, used by callbacks; never dereferenced on worker threads
    // Worker threads only ever need these snapshots, copied once on the client thread (Phase 1)
    // or once on the worker thread under uploadMutex after preflightStart (Phase 2).
    LocalPath mLocalPath; // Phase 1: set in constructor
    std::array<byte, SymmCipher::KEYLENGTH>
        mTransferKey{}; // Phase 2: set in snapshotCryptoMaterial()
    int64_t mCtrIv{0}; // Phase 2
    std::unique_ptr<FileAccess> mFA{}; // blocking-opened on first read
    // Atomic so readers that do not hold engineMutex (e.g. the workGeneration() accessor
    // at wsupload.cpp ~700) observe a well-defined value. Writers still serialise via
    // engineMutex; the atomic adds cheap defence for future callers that forget.
    std::atomic<std::uint64_t> mWorkGeneration{1};
    std::mutex mReadMutex; // needed for Android because of lseek64+read
    std::atomic<unsigned> mActiveIO{0};

    std::uint32_t mFileNo{0};

    // Saved session URL to allow best-effort resume after restart.
    std::string mSessionUrlHint;

    // progress/state
    m_off_t mSize{0};
    m_off_t mHeadPos{0};
    m_off_t mBytesConfirmed{0};
    m_off_t mAttemptBaseConfirmed{0};
    m_off_t mLastReportedBytesConfirmed{0};
    m_off_t mNumRequests{0};
    m_off_t mNumFailedRequests{0};
    dstime mFirstAckTime{0};
    m_off_t mLastProgressReportBytes{0};
    dstime mLastProgressReportDs{0};
    mutable SpeedController mAckSpeedController{};
    m_time_t mMtime{0};
    UploadEngine::FailureDisposition mReadFailureDisposition{
        UploadEngine::FailureDisposition::Retryable};

    m_off_t mBytesSinceLastStat = 0;
    m_off_t mStatIntervalBytes = STAT_INTERVAL_LARGE;

    static constexpr m_off_t STAT_INTERVAL_LARGE = 8 * kMiB; // 8 MiB
    static constexpr m_off_t STAT_INTERVAL_SMALL = 2 * kMiB; // 2 MiB

    bool mEofSet{false};
    bool mAborted{false};
    bool mPaused{false};

    dstime mUploadStartTime{0};
    dstime mUploadCompletionTime{0};
    dstime mUploadFailedTime{0};
    dstime mRetryUntil{0};

    // Server-confirmed chunk MAC updates awaiting application on the client thread.
    std::vector<chunkmac_map> mConfirmedChunkMacs;
#ifndef NDEBUG
    bool mFirstByteSentForStats{false};
#endif
};

} // namespace ws
} // namespace mega

#endif // MEGA_USE_WSUPLOAD

#endif // MEGA_TRANSFER_WS_WS_UPLOAD_FILE_H
